export interface UnitType {
  type: string;
  size: string;
  layouts: string[];
}

export interface Property {
  id: string;
  slug: string;
  name: string;
  nameZh?: string;
  area: string;
  district?: string;
  category?: 'luxury' | 'waterfront' | 'city' | 'resort';
  type?: string | string[];
  price: {
    sgd: number;
    myr: number;
  };
  priceRange?: string;
  specs: {
    beds: number | string;
    baths: number | string;
    size: number | string;
  };
  yield: number;
  rtsDistance: string;
  tenure: string;
  leaseYears?: number;
  completion?: string;
  completionYear?: string;
  status?: 'available' | 'limited' | 'sold-out' | 'coming-soon';
  image: string;
  images: string[];
  tourUrl?: string;
  tourProvider?: 'matterport' | 'kuula' | 'generic';
  description: string;
  highlights?: string[];
  unitTypes?: UnitType[];
  features?: string[];
  developer?: string;
  towers?: string[];
  address?: string;
  coordinates: [number, number];
  featured?: boolean;
}

export const properties: Property[] = [
  {
    id: "rf-princess-cove-overview",
    slug: "rf-princess-cove-overview",
    name: "R&F Princess Cove",
    nameZh: "富力公主湾",
    area: "Tanjung Puteri",
    district: "Johor Bahru Waterfront",
    category: "luxury",
    price: { sgd: 113000, myr: 380000 },
    priceRange: "RM380,000 — RM5,000,000",
    specs: { beds: "Studio - 4 Bed", baths: "1-4", size: "313 - 2,200" },
    yield: 7.6,
    rtsDistance: "1km",
    tenure: "Freehold",
    completionYear: "Mixed (Completed + New Launch)",
    status: "available",
    description: "R&F Princess Cove is a 116-acre integrated waterfront development by R&F Properties, located in Bukit Chagar, Johor Bahru. Strategically positioned just 1km from the CIQ checkpoint and the upcoming RTS Link station, it is one of the largest mixed-use developments in the Johor Bahru city centre. The masterplan encompasses residential towers across multiple phases, a retail mall, serviced apartments, and commercial spaces — creating a self-contained waterfront city.",
    highlights: [
      "116-acre integrated waterfront mega project",
      "1km to CIQ / RTS Link Station",
      "Freehold tenure across all phases",
      "Multiple phases — completed & new launches",
      "Connected to R&F Mall via sheltered bridge",
      "5.5 - 8% rental yields",
    ],
    unitTypes: [],
    image: "/images/properties/rf-princess-cove-overview/hero.jpg",
    images: ["/images/properties/rf-princess-cove-overview/hero.jpg"],
    tourUrl: "https://www.actsugi.com/rfprincesscovejb/",
    tourProvider: "generic",
    featured: true,
    type: ["luxury", "waterfront"],
    coordinates: [103.7679, 1.4591],
    developer: "R&F Properties",
    towers: [],
    address: "Jalan Tanjung Puteri, 80300 Johor Bahru",
  },
  {
    id: "rf-princess-cove-phase-1",
    slug: "rf-princess-cove-phase-1",
    name: "R&F Princess Cove Phase 1",
    nameZh: "富力公主湾一期",
    area: "Tanjung Puteri",
    district: "Johor Bahru Waterfront",
    category: "luxury",
    price: { sgd: 149000, myr: 500000 },
    priceRange: "RM500,000 — RM2,500,000",
    specs: { beds: "1-4", baths: "1-3", size: "469-1,386" },
    yield: 6.8,
    rtsDistance: "500m",
    tenure: "Freehold",
    completionYear: "Completed 2019",
    status: "sold-out",
    description: "The iconic twin-tower development and tallest residential building in Southeast Asia. Phase 1 features 33 luxurious layouts across 7 towers (A1-A7) with panoramic views of the Johor Strait and Singapore skyline. HOPSCA integrated development with hotel, offices, parks, shopping, and clubhouse.",
    highlights: [
      "Tallest residential in Southeast Asia",
      "33 luxurious layouts to choose from",
      "HOPSCA integrated development",
      "5 minutes to JB-SG RTS Link",
      "650m sheltered link bridge to CIQ",
      "Connected to R&F Mall"
    ],
    unitTypes: [
      { type: "1 Bedroom", size: "469-543 sqft", layouts: ["Type D", "Type V2"] },
      { type: "2 Bedroom", size: "800-873 sqft", layouts: ["Type U6", "Type I Sub2", "Type G", "Type I"] },
      { type: "2+1 Bedroom", size: "1,074 sqft", layouts: ["Type N"] },
      { type: "3 Bedroom", size: "1,052-1,139 sqft", layouts: ["Type A1", "Type J1", "Type K", "Type M1", "Type F"] },
      { type: "4 Bedroom", size: "1,386 sqft", layouts: ["Type H"] },
      { type: "Dual Key", size: "1,286-1,318 sqft", layouts: ["Type E", "Type E2", "Type V3"] }
    ],
    image: "/images/properties/rf-princess-cove-phase-1/hero.jpg",
    images: ["/images/properties/rf-princess-cove-phase-1/hero.jpg"],
    tourUrl: "https://infishow.ideamake.cn/icp/xinshanguojicheng_10418/weishapanfuzhi_10.html",
    tourProvider: "generic",
    featured: true,
    type: ["luxury", "waterfront"],
    coordinates: [103.7679, 1.4591],
    developer: "R&F Properties",
    towers: ["A1", "A2", "A3", "A3A", "A5", "A6", "A7"],
    address: "Jalan Tanjung Puteri, 80300 Johor Bahru",
  },
  {
    id: "rf-princess-cove-phase-2",
    slug: "rf-princess-cove-phase-2",
    name: "R&F Princess Cove Phase 2 - Seine Region",
    nameZh: "富力公主湾二期 塞纳天地",
    area: "Tanjung Puteri",
    district: "Johor Bahru Waterfront",
    category: "luxury",
    price: { sgd: 179000, myr: 600000 },
    priceRange: "RM600,000 — RM3,000,000",
    specs: { beds: "Studio-3", baths: "1-2", size: "468-1,317" },
    yield: 7.2,
    rtsDistance: "650m",
    tenure: "Freehold",
    completionYear: "Completed 2022",
    status: "limited",
    description: "Seine Region offers exclusive sea view units overlooking the JB-Singapore Causeway with panoramic views of Singapore's cityscape. Features infinity swimming pool, gym, yoga room, jogging track at the sky lounge. Adjacent to R&F Marina Place with IMAX theatre, yacht club, and fashion boutiques.",
    highlights: [
      "Exclusive panoramic sea views",
      "6 minutes to JB-SG RTS Link",
      "Sky lounge with infinity pool",
      "Adjacent to Opera House & Cineplex",
      "Private Yacht Club access",
      "Most viewed rental project in Malaysia"
    ],
    unitTypes: [
      { type: "Studio", size: "468-471 sqft", layouts: ["Type D", "Type D Sub2"] },
      { type: "1 Bedroom", size: "544 sqft", layouts: ["Type V6"] },
      { type: "2 Bedroom", size: "767-933 sqft", layouts: ["Type V7M", "Type V7", "Type B", "Type B Sub2", "Type V5", "Type V5M", "Type U1", "Type U1 Sub2", "Type G"] },
      { type: "3 Bedroom", size: "1,105-1,181 sqft", layouts: ["Type M1 Sub2", "Type M1", "Type A", "Type A1"] },
      { type: "Dual Key", size: "1,317 sqft", layouts: ["Type E"] }
    ],
    image: "/images/properties/rf-princess-cove-phase-2/hero.jpg",
    images: ["/images/properties/rf-princess-cove-phase-2/hero.jpg"],
    tourUrl: "https://infishow.ideamake.cn/icp/xinshanguojicheng_10418/weishapanfuzhi_10.html",
    tourProvider: "generic",
    featured: true,
    type: ["luxury", "waterfront", "city"],
    coordinates: [103.7679, 1.4591],
    developer: "R&F Properties",
    towers: ["B1", "B2", "B3", "B3A"],
    address: "Jalan Tanjung Puteri, 80300 Johor Bahru",
  },
  {
    id: "rf-princess-cove-phase-3",
    slug: "rf-princess-cove-phase-3",
    name: "R&F Princess Cove Phase 3",
    nameZh: "富力公主湾三期",
    area: "Tanjung Puteri",
    district: "Johor Bahru Waterfront",
    category: "luxury",
    price: { sgd: 113000, myr: 380000 },
    priceRange: "RM380,000 — RM5,200,000",
    specs: { beds: "Studio - 4", baths: "1 - 3", size: "313 - 1,555" },
    yield: 7.6,
    rtsDistance: "650m",
    tenure: "Freehold",
    completionYear: "Q1 2028",
    status: "coming-soon",
    description: "Phase 3 — New Casa Suites at Mercu 3 offers studio to 4-bedroom layouts from 313 to 1,555 sqft. Connected to R&F Mall via a 650m sheltered link bridge to CIQ and direct RTS connection to Singapore.",
    highlights: ["650m sheltered link to CIQ", "Freehold tenure", "Urban Skypark amenities", "Studio to 4-bedroom layouts"],
    unitTypes: [],
    image: "/images/properties/rf-princess-cove-overview/hero.jpg",
    images: ["/images/properties/rf-princess-cove-overview/hero.jpg"],
    tourUrl: "https://www.actsugi.com/rfprincesscovejb/",
    tourProvider: "generic",
    featured: true,
    type: ["luxury"],
    coordinates: [103.7679, 1.4591],
    developer: "R&F Properties",
    towers: [],
    address: "Jalan Tanjung Puteri, 80300 Johor Bahru",
  },
  {
    id: "ctc-skyone-bukit-chagar",
    slug: "ctc-skyone-bukit-chagar",
    name: "CTC Skyone",
    area: "Bukit Chagar",
    district: "Johor Bahru City",
    category: "city",
    price: { sgd: 149000, myr: 500000 },
    priceRange: "RM500,000 — RM1,200,000",
    specs: { beds: "1-3", baths: "1-2", size: "450 - 950" },
    yield: 6.5,
    rtsDistance: "300m",
    tenure: "Freehold",
    completionYear: "2030 Q2",
    status: "available",
    description: "CTC Skyone is a freehold high-rise development strategically located only 300 metres from the RTS Link station, making it one of the most convenient residences for cross-border commuters. Situated beside Sheraton Hotel and SKS City Mall, residents can enjoy the best of city living with shopping, dining, and lifestyle conveniences right at their doorstep. All unit layouts are thoughtfully designed and can be converted into dual-key configurations, providing extra flexibility for homeowners and investors alike.",
    highlights: [
      "Just 300m from RTS Link station",
      "Beside Sheraton Hotel & SKS City Mall",
      "Freehold in JB city centre",
      "All layouts convertible to dual-key",
      "1,605 units across 1.64 acres",
    ],
    unitTypes: [],
    image: "/images/properties/ctc-skyone-bukit-chagar/hero.jpg",
    images: [
      "/images/properties/ctc-skyone-bukit-chagar/hero.jpg",
      "/images/properties/ctc-skyone-bukit-chagar/gallery-1.jpg",
    ],
    tourUrl: "https://goprop360.com/360vr/CTC/",
    tourProvider: "generic",
    featured: false,
    type: ["city"],
    coordinates: [103.7619, 1.4706],
    developer: "CTC Group",
    towers: [],
    address: "Bukit Chagar, 80300 Johor Bahru",
  },
{
    id: "paragon-gateway-taman-suria",
    slug: "paragon-gateway-taman-suria",
    name: "Paragon Gateway Taman Suria",
    area: "Taman Suria",
    district: "Johor Bahru City",
    category: "city" as const,
    price: { sgd: 149253, myr: 500000 },
    priceRange: "RM500K+",
    specs: { beds: "1-3", baths: "1-2", size: "450 - 1,200" },
    yield: 6.0,
    rtsDistance: "TBD",
    tenure: "Freehold",
    completionYear: "2027 Q2",
    status: "available" as const,
    description: "1+1 Bedroom VR showroom: https://vr.3d66.com/vr/index_detail_2873651.asp",
    highlights: [
      "Affordable pricing in Johor Bahru city centre",
      "Prime location beside Tebrau Highway",
      "5 mins to major malls – KSL City, Mid Valley Southkey, Aeon Tebrau City & IKEA",
      "48 retail units at doorstep for everyday convenience",
      "Comfortable layouts compared to CIQ area developments",
      "Shuttle bus service + future ART line station right in front"
    ],
    unitTypes: [],
    image: "/images/properties/paragon-gateway-taman-suria/hero.jpg",
    images: [
      "/images/properties/paragon-gateway-taman-suria/hero.jpg",
      "/images/properties/paragon-gateway-taman-suria/gallery-1.jpg"
    ],
    tourUrl: "https://vr.3d66.com/vr/index_detail_2898904.asp",
    tourProvider: "generic" as const,
    featured: false,
    type: ["city"],
    coordinates: [103.7606, 1.5025] as [number, number],
    developer: "",
    towers: [],
    address: "Taman Suria, Johor Bahru",
  },
  {
    id: "maxim-the-address-taman-pelangi",
    slug: "maxim-the-address-taman-pelangi",
    name: "Maxim The Address Taman Pelangi",
    area: "Taman Pelangi",
    district: "Johor Bahru City",
    category: "city" as const,
    price: { sgd: 179104, myr: 600000 },
    priceRange: "RM600K+",
    specs: { beds: "1-3", baths: "1-2", size: "450 - 1,200" },
    yield: 6.0,
    rtsDistance: "TBD",
    tenure: "Freehold",
    completionYear: "2030 Q1",
    status: "available" as const,
    description: "Maxim The Address is strategically located at Taman Pelangi, right beside Tebrau Highway, offering excellent accessibility and everyday convenience. Surrounded by established shop houses, residents can easily settle daily needs within walking distance. Popular shopping malls such as KSL City Mall and Plaza Pelangi are just minutes away, making this a highly practical living location.",
    highlights: [
      "Prime location at Taman Pelangi, beside Tebrau Highway",
      "Surrounded by shop houses, amenities, and daily conveniences",
      "Walking distance / short drive to KSL City Mall & Plaza Pelangi",
      "Affordable pricing with medium-end quality finishings",
      "Attractive rental yield of ~6% based on current market",
      "Strong demand from local buyers & tenants – a true local-favored product"
    ],
    unitTypes: [],
    image: "/images/properties/maxim-the-address-taman-pelangi/hero.jpg",
    images: [
      "/images/properties/maxim-the-address-taman-pelangi/hero.jpg",
      "/images/properties/maxim-the-address-taman-pelangi/gallery-1.jpg",
      "/images/properties/maxim-the-address-taman-pelangi/gallery-2.jpg"
    ],
    tourUrl: "https://goprop360.com/360vr/Maxim_Pelangi/",
    tourProvider: "generic" as const,
    featured: false,
    type: ["city"],
    coordinates: [103.7646, 1.4826] as [number, number],
    developer: "",
    towers: [],
    address: "Taman Pelangi, Johor Bahru",
  },
  {
    id: "golf-villa-forest-city-sfz",
    slug: "golf-villa-forest-city-sfz",
    name: "Golf Villa Forest City (SFZ)",
    area: "Forest City",
    district: "Iskandar Puteri",
    category: "city" as const,
    price: { sgd: 298507, myr: 1000000 },
    priceRange: "RM1mil+",
    specs: { beds: "1-3", baths: "1-2", size: "450 - 1,200" },
    yield: 6.0,
    rtsDistance: "TBD",
    tenure: "Freehold",
    completionYear: "2018",
    status: "available" as const,
    description: "Forest City Golf Villa is an exclusive freehold landed development located within the award-winning Forest City township in Iskandar Puteri, Johor Bahru.",
    highlights: [
      "Freehold luxury villas within Forest City township",
      "Direct golf course frontage and private gardens",
      "Resort-style clubhouse, and leisure facilities",
      "Close to Singapore via Second Link Expressway",
      "Surrounded by international schools and retail amenities"
    ],
    unitTypes: [],
    image: "/images/properties/golf-villa-forest-city-sfz/hero.jpg",
    images: [
      "/images/properties/golf-villa-forest-city-sfz/hero.jpg",
      "/images/properties/golf-villa-forest-city-sfz/gallery-1.jpg",
      "/images/properties/golf-villa-forest-city-sfz/gallery-2.jpg",
      "/images/properties/golf-villa-forest-city-sfz/gallery-3.jpg",
      "/images/properties/golf-villa-forest-city-sfz/gallery-4.jpg",
      "/images/properties/golf-villa-forest-city-sfz/gallery-5.jpg"
    ],
    featured: false,
    type: ["city"],
    coordinates: [103.5537, 1.4129] as [number, number],
    developer: "",
    towers: [],
    address: "Forest City, Johor Bahru",
  },
  {
    id: "m-grand-minori-taman-pelangi",
    slug: "m-grand-minori-taman-pelangi",
    name: "M Grand Minori Taman Pelangi",
    area: "Taman Pelangi",
    district: "Johor Bahru City",
    category: "city" as const,
    price: { sgd: 149253, myr: 500000 },
    priceRange: "RM500K+",
    specs: { beds: "1-3", baths: "1-2", size: "450 - 1,200" },
    yield: 6.0,
    rtsDistance: "TBD",
    tenure: "Freehold",
    completionYear: "2030 Q1",
    status: "available" as const,
    description: "M Grand Minori is a freehold, mixed-use development by Mah Sing Group, located at Jalan Kuning, Taman Pelangi in central Johor Bahru. This iconic project spans about 5.99 acres and features modern high-rise towers of up to 59 floors, offering a wide selection of units from studios to spacious multi-bedroom layouts, including dual-key optionsthat provide excellent flexibility for rental and investment.",
    highlights: [
      "Prime Taman Pelangi address – central JB with strong local demand",
      "Surrounded by daily amenities, lifestyle shops, F&B, and all major banks",
      "Freehold, mixed-use concept with residential + retail",
      "Flexible layouts with dual-key option – great for rental yield",
      "3 km to Bukit Chagar RTS – excellent cross-border connectivity",
      "Affordable entry price for a high-rise city residence"
    ],
    unitTypes: [],
    image: "/images/properties/m-grand-minori-taman-pelangi/hero.jpg",
    images: [
      "/images/properties/m-grand-minori-taman-pelangi/hero.jpg",
      "/images/properties/m-grand-minori-taman-pelangi/gallery-1.jpg",
      "/images/properties/m-grand-minori-taman-pelangi/gallery-2.jpg"
    ],
    tourUrl: "https://framemakers-creative.com/mgrandminori/",
    tourProvider: "generic" as const,
    featured: false,
    type: ["city"],
    coordinates: [103.7703, 1.4783] as [number, number],
    developer: "",
    towers: [],
    address: "Taman Pelangi, Johor Bahru",
  },
  {
    id: "the-astaka-one-bukit-senyum",
    slug: "the-astaka-one-bukit-senyum",
    name: "The Astaka One Bukit Senyum",
    area: "Bukit Senyum",
    district: "Johor Bahru City",
    category: "city" as const,
    price: { sgd: 298507, myr: 1000000 },
    priceRange: "Rm1mil+",
    specs: { beds: "1-3", baths: "1-2", size: "450 - 1,200" },
    yield: 6.0,
    rtsDistance: "TBD",
    tenure: "Freehold",
    completionYear: "2018",
    status: "available" as const,
    description: "The Astaka is Johor Bahru’s most iconic luxury condominium, located within the prestigious One Bukit Senyumintegrated development. Standing at 278 metres tall, it is currently the tallest residential building in Southeast Asia, redefining the city skyline with its architectural elegance. Designed for ultra-high-end living, The Astaka offers spacious layouts, private lift lobbies, and 6-star facilities, making it the top choice for discerning homeowners and investors seeking a world-class residence.",
    highlights: [
      "Tallest residential tower in Southeast Asia (278m)",
      "Part of One Bukit Senyum integrated township – future offices, mall & hotel",
      "Only 800m to JB CIQ & RTS Link – seamless access to Singapore",
      "Ultra-luxury layouts with private lift lobbies",
      "Prestigious address with strong capital appreciation potential"
    ],
    unitTypes: [],
    image: "/images/properties/the-astaka-one-bukit-senyum/hero.jpg",
    images: [
      "/images/properties/the-astaka-one-bukit-senyum/hero.jpg",
      "/images/properties/the-astaka-one-bukit-senyum/gallery-1.jpg",
      "/images/properties/the-astaka-one-bukit-senyum/gallery-2.jpg",
      "/images/properties/the-astaka-one-bukit-senyum/gallery-3.jpg"
    ],
    featured: false,
    type: ["city"],
    coordinates: [103.7625, 1.4735] as [number, number],
    developer: "",
    towers: [],
    address: "Bukit Senyum, Johor Bahru",
  },
  {
    id: "elysia-park-medini",
    slug: "elysia-park-medini",
    name: "Elysia Park Medini",
    area: "Medini",
    district: "Iskandar Puteri",
    category: "city" as const,
    price: { sgd: 0, myr: 0 },
    priceRange: "Any price+",
    specs: { beds: "1-3", baths: "1-2", size: "450 - 1,200" },
    yield: 6.0,
    rtsDistance: "TBD",
    tenure: "Lease",
    completionYear: "2019",
    status: "available" as const,
    description: "Elysia Park Residence is a completed leasehold condominium by BCB Berhad, finished in 2019. Located in the heart of Medini, Iskandar Puteri, this project features 981 units across three 44-storey towers, offering a wide range of layouts from compact studios to spacious family homes — including exclusive duplex units.",
    highlights: [
      "Completed in 2019 – actual units available, ready for move-in",
      "981 Units / 3 Towers – layouts from studios to family homes",
      "Duplex Units Available – spacious designs with double-volume living",
      "Park Beside the Residence – direct access to outdoor greenery",
      "Comprehensive Facilities – pool, gym, sky garden, BBQ, playground & more",
      "Prime Medini Location – near Mall of Medini, LEGOLAND, Gleneagles Hospital & schools"
    ],
    unitTypes: [],
    image: "/images/properties/elysia-park-medini/hero.jpg",
    images: [
      "/images/properties/elysia-park-medini/hero.jpg",
      "/images/properties/elysia-park-medini/gallery-1.jpg",
      "/images/properties/elysia-park-medini/gallery-2.jpg"
    ],
    featured: false,
    type: ["city"],
    coordinates: [103.6353, 1.4257] as [number, number],
    developer: "",
    towers: [],
    address: "Medini, Johor Bahru",
  },
  {
    id: "the-arden-one-bukit-senyum",
    slug: "the-arden-one-bukit-senyum",
    name: "The Arden One Bukit Senyum",
    area: "Bukit Senyum",
    district: "Johor Bahru City",
    category: "city" as const,
    price: { sgd: 298507, myr: 1000000 },
    priceRange: "RM1mil+",
    specs: { beds: "1-3", baths: "1-2", size: "450 - 1,200" },
    yield: 6.0,
    rtsDistance: "TBD",
    tenure: "Freehold",
    completionYear: "2030 Q1",
    status: "available" as const,
    description: "The Arden is a premium landmark serviced apartment by Astaka-Kimlun, rising 68 storeys tall (~260m) in Johor Bahru’s emerging CBD One Bukit Senyum. As a freehold development on approximately 1.73 acres, it comprises 618 residential units + 4 commercial lots, with built-ups ranging from 797 to 1,700 sq ft. Targeted completion is around 2029–2030, with prices from RM1,300 to RM1,500 psf. Its strategic location is just 600m from the RTS Link and 800m from CIQ, giving unparalleled cross-border access.",
    highlights: [
      "One of Johor Bahru’s tallest landmark residences after The Astaka",
      "Targeted at high-end homeowners / investors / property collectors",
      "Projected new shopping mall (OBS) nearby to boost lifestyle & amenities",
      "Premium finishes & elite design standards",
      "Strong address prestige & excellent skyline views"
    ],
    unitTypes: [],
    image: "/images/properties/the-arden-one-bukit-senyum/hero.jpg",
    images: [
      "/images/properties/the-arden-one-bukit-senyum/hero.jpg",
      "/images/properties/the-arden-one-bukit-senyum/gallery-1.jpg",
      "/images/properties/the-arden-one-bukit-senyum/gallery-2.jpg"
    ],
    tourUrl: "https://vr.properly.com.my/thearden_type_b/",
    tourProvider: "generic" as const,
    featured: false,
    type: ["city"],
    coordinates: [103.7605, 1.4733] as [number, number],
    developer: "",
    towers: [],
    address: "Bukit Senyum, Johor Bahru",
  },
  {
    id: "skypark-kepler-lido-waterfront-boulevard",
    slug: "skypark-kepler-lido-waterfront-boulevard",
    name: "Skypark Kepler Lido Waterfront Boulevard",
    area: "Lido Waterfront",
    district: "Johor Bahru City",
    category: "city" as const,
    price: { sgd: 149253, myr: 500000 },
    priceRange: "RM500K+",
    specs: { beds: "1-3", baths: "1-2", size: "450 - 1,200" },
    yield: 6.0,
    rtsDistance: "TBD",
    tenure: "Freehold",
    completionYear: "2029 Q4",
    status: "available" as const,
    description: "Skypark Kepler is the first branded residence in Johor Bahru managed by Banyan Tree, a world-renowned international hospitality group. Positioned within Lido Waterfront Boulevard, a visionary development planned as the next CBD of Johor Bahru inspired by Singapore’s Marina Bay, this project carries strong long-term growth and sustainable investment value.",
    highlights: [
      "First Branded Residence in JB – Managed by Banyan Tree, a world-renowned hospitality group",
      "Prime Waterfront Address – Situated along Johor Bahru’s Lido Waterfront Boulevard",
      "Next CBD Potential – Masterplanned as the future CBD of JB, inspired by Singapore’s Marina Bay",
      "Sustainable Investment Value – Strong growth prospects & global appeal for investors",
      "World-Class Lifestyle – Seamless mix of residences, business, leisure & entertainment"
    ],
    unitTypes: [],
    image: "/images/properties/skypark-kepler-lido-waterfront-boulevard/hero.jpg",
    images: [
      "/images/properties/skypark-kepler-lido-waterfront-boulevard/hero.jpg",
      "/images/properties/skypark-kepler-lido-waterfront-boulevard/gallery-1.jpg"
    ],
    tourUrl: "https://www.actsugi.com/LidoWaterfrontBoulevard/",
    tourProvider: "generic" as const,
    featured: false,
    type: ["city"],
    coordinates: [103.7459, 1.4557] as [number, number],
    developer: "",
    towers: [],
    address: "Lido Waterfront, Johor Bahru",
  },
  {
    id: "suria-hill",
    slug: "suria-hill",
    name: "Suria Hill Iskandar Puteri",
    area: "Johor Bahru",
    district: "Johor Bahru",
    category: "city" as const,
    price: { sgd: 298507, myr: 1000000 },
    priceRange: "Rm1mil+",
    specs: { beds: "1-3", baths: "1-2", size: "450 - 1,200" },
    yield: 6.0,
    rtsDistance: "TBD",
    tenure: "Freehold",
    completionYear: "2026 Q4",
    status: "available" as const,
    description: "Suria Hill is an exclusive freehold bungalow development located in Iskandar Puteri, Johor Bahru , spanning 65 acres of serene, elevated land . Comprising only 114 bungalow units , this low-density enclave offers residents an unmatched sense of privacy, space, and tranquility within one of Johor’s most prestigious residential zones.",
    highlights: [
      "Freehold bungalow development on 65 acres of elevated land",
      "Only 114 exclusive units – low-density & private community",
      "Spacious layouts with modern luxury design",
      "Lush green environment with serene surroundings",
      "Located within Iskandar Puteri, near major amenities & highways",
      "Rare opportunity for premium landed home ownership in JB"
    ],
    unitTypes: [],
    image: "/images/properties/suria-hill/hero.jpg",
    images: [
      "/images/properties/suria-hill/hero.jpg"
    ],
    tourUrl: "https://www.suriahills.com.my/suriahills360vt/",
    tourProvider: "generic" as const,
    featured: false,
    type: ["city"],
    coordinates: [103.6466, 1.4487] as [number, number],
    developer: "",
    towers: [],
    address: "Johor Bahru, Johor Bahru",
  },
  {
    id: "parkland-by-the-river-permas",
    slug: "parkland-by-the-river-permas",
    name: "Parkland by the river Permas",
    area: "Permas Jaya",
    district: "Johor Bahru East",
    category: "city" as const,
    price: { sgd: 0, myr: 0 },
    priceRange: "N/A+",
    specs: { beds: "1-3", baths: "1-2", size: "450 - 1,200" },
    yield: 6.0,
    rtsDistance: "TBD",
    tenure: "Freehold",
    completionYear: "2028 Q2",
    status: "available" as const,
    description: "Parkland by the River is a freehold residential development located in Permas Jaya, Johor Bahru , offering scenic river views and modern urban comfort. Developed by Parkland Group , this project provides affordable yet stylish homes ideal for local homeowners and investors seeking value and convenience within a mature township.",
    highlights: [
      "Located at Permas Jaya with beautiful river view",
      "Freehold development by Parkland Group",
      "Affordable pricing suitable for local buyers",
      "Choices of 1, 2 & 3-bedroom layouts",
      "Full condominium facilities and modern lifestyle environment",
      "Convenient access to JB city centre & major highways"
    ],
    unitTypes: [],
    image: "/images/properties/parkland-by-the-river-permas/hero.jpg",
    images: [
      "/images/properties/parkland-by-the-river-permas/hero.jpg",
      "/images/properties/parkland-by-the-river-permas/gallery-1.jpg",
      "/images/properties/parkland-by-the-river-permas/gallery-2.jpg",
      "/images/properties/parkland-by-the-river-permas/gallery-3.jpg"
    ],
    featured: false,
    type: ["city"],
    coordinates: [103.7992, 1.4946] as [number, number],
    developer: "",
    towers: [],
    address: "Permas Jaya, Johor Bahru",
  },
  {
    id: "skyline-one-sentosa-taman-sentosa",
    slug: "skyline-one-sentosa-taman-sentosa",
    name: "Skyline One Sentosa Taman Sentosa",
    area: "Taman Sentosa",
    district: "Johor Bahru City",
    category: "city" as const,
    price: { sgd: 149253, myr: 500000 },
    priceRange: "RM500K+",
    specs: { beds: "1-3", baths: "1-2", size: "450 - 1,200" },
    yield: 6.0,
    rtsDistance: "TBD",
    tenure: "Freehold",
    completionYear: "2030 Q2",
    status: "available" as const,
    description: "Skyline One Sentosa is a redevelopment of the former Plaza Sentosa, developed by TSLAW, a reputable local builder. The project sits in mature Taman Sentosa — a well-established neighbourhood comparable to Taman Pelangiand Taman Century — offering stable community vibes and ready-made amenities. With practical layouts and sensible pricing, Skyline One Sentosa is ideal for owner-occupiers seeking comfortable city living and investors looking for steady rental demand in an established area.",
    highlights: [
      "Redevelopment of Plaza Sentosa — refreshed site with proven location history",
      "Developer: TSLAW — reputable local builder with solid track record",
      "Mature Neighbourhood — Taman Sentosa (like Taman Pelangi & Taman Century)",
      "Established Amenities — shops, schools, eateries and daily conveniences nearby",
      "Owner & Investor Friendly — practical layouts and stable rental prospects"
    ],
    unitTypes: [],
    image: "/images/properties/skyline-one-sentosa-taman-sentosa/hero.jpg",
    images: [
      "/images/properties/skyline-one-sentosa-taman-sentosa/hero.jpg",
      "/images/properties/skyline-one-sentosa-taman-sentosa/gallery-1.jpg",
      "/images/properties/skyline-one-sentosa-taman-sentosa/gallery-2.jpg"
    ],
    tourUrl: "https://goprop360.com/360vr/TSLAW/",
    tourProvider: "generic" as const,
    featured: false,
    type: ["city"],
    coordinates: [103.7658, 1.4922] as [number, number],
    developer: "",
    towers: [],
    address: "Taman Sentosa, Johor Bahru",
  },
  {
    id: "the-m-macrolink-medini",
    slug: "the-m-macrolink-medini",
    name: "The M Macrolink Medini",
    area: "Medini",
    district: "Iskandar Puteri",
    category: "city" as const,
    price: { sgd: 0, myr: 0 },
    priceRange: "Any price+",
    specs: { beds: "1-3", baths: "1-2", size: "450 - 1,200" },
    yield: 6.0,
    rtsDistance: "TBD",
    tenure: "Lease Title",
    completionYear: "2020",
    status: "available" as const,
    description: "The M Macrolink is a completed serviced residence built in 2020, under a lease title from Iskandar Investment Berhad (IIB). Located in the heart of Medini, Iskandar Puteri, it offers buyers the opportunity to view actual units and move in immediately. Developed by Macrolink International Land, the project combines smart-home features, modern layouts, and resort-style living.",
    highlights: [
      "Completed in 2020 – actual units available for viewing, ready to move in",
      "Lease Title under Iskandar Investment Berhad (IIB)",
      "10-Acre Recreational Park – green open space for leisure & outdoor activities",
      "40+ Lifestyle Facilities – infinity pool, gym, sky gardens & more",
      "Smart Home Features with partially furnished units",
      "Prime Location – near LEGOLAND, Gleneagles Medini, Puteri Harbour & international schools"
    ],
    unitTypes: [],
    image: "/images/properties/the-m-macrolink-medini/hero.jpg",
    images: [
      "/images/properties/the-m-macrolink-medini/hero.jpg",
      "/images/properties/the-m-macrolink-medini/gallery-1.jpg",
      "/images/properties/the-m-macrolink-medini/gallery-2.jpg"
    ],
    tourUrl: "https://360media.com.my/macrolink-vr",
    tourProvider: "generic" as const,
    featured: false,
    type: ["city"],
    coordinates: [103.6238, 1.4186] as [number, number],
    developer: "",
    towers: [],
    address: "Medini, Johor Bahru",
  },
  {
    id: "nigella-park-forest-city-sfz",
    slug: "nigella-park-forest-city-sfz",
    name: "Nigella Park Forest City (SFZ)",
    area: "Forest City",
    district: "Iskandar Puteri",
    category: "city" as const,
    price: { sgd: 149253, myr: 500000 },
    priceRange: "RM500K+",
    specs: { beds: "1-3", baths: "1-2", size: "450 - 1,200" },
    yield: 6.0,
    rtsDistance: "TBD",
    tenure: "Freehold",
    completionYear: "2017",
    status: "available" as const,
    description: "Nigella Park presents an exclusive collection of luxury penthouse residences within the prestigious Forest City township in Iskandar Puteri, Johor Bahru.",
    highlights: [
      "All-penthouse concept with private lift and sea view",
      "From 282 sqm to 358 sqm (private pool in 358 sqm unit)",
      "Freehold residence in Forest City duty-free zone",
      "Surrounded by international schools, shops & resort facilities",
      "Easy access to Singapore via Second Link"
    ],
    unitTypes: [],
    image: "/images/properties/nigella-park-forest-city-sfz/hero.jpg",
    images: [
      "/images/properties/nigella-park-forest-city-sfz/hero.jpg",
      "/images/properties/nigella-park-forest-city-sfz/gallery-1.jpg",
      "/images/properties/nigella-park-forest-city-sfz/gallery-2.jpg",
      "/images/properties/nigella-park-forest-city-sfz/gallery-3.jpg"
    ],
    featured: false,
    type: ["city"],
    coordinates: [103.5962, 1.3405] as [number, number],
    developer: "",
    towers: [],
    address: "Forest City, Johor Bahru",
  },
  {
    id: "southern-marina-puteri-harbour",
    slug: "southern-marina-puteri-harbour",
    name: "Southern Marina Puteri Harbour",
    area: "Puteri Harbour",
    district: "Iskandar Puteri",
    category: "city" as const,
    price: { sgd: 149253, myr: 500000 },
    priceRange: "RM500K+",
    specs: { beds: "1-3", baths: "1-2", size: "450 - 1,200" },
    yield: 6.0,
    rtsDistance: "TBD",
    tenure: "Freehold",
    completionYear: "2018",
    status: "available" as const,
    description: "Southern Marina Residences is a completed seafront development located directly in front of the Puteri Harbour International Ferry Terminal. Built with high-end quality and designed for low-density living, the residences offer spacious layouts with stunning views of the Straits of Johor and the marina.",
    highlights: [
      "Completed & Ready to Move In – actual units available for viewing",
      "Prime Seafront Location – directly opposite Puteri Harbour International Ferry Terminal",
      "Low-Density Development – private, exclusive living environment",
      "High-End Quality – premium finishes & modern architecture",
      "Spacious Seaview Units – enjoy panoramic views of marina & Straits of Johor",
      "Lifestyle & Connectivity – walk to harbour promenade, near schools, healthcare & easy access to Singapore"
    ],
    unitTypes: [],
    image: "/images/properties/southern-marina-puteri-harbour/hero.jpg",
    images: [
      "/images/properties/southern-marina-puteri-harbour/hero.jpg",
      "/images/properties/southern-marina-puteri-harbour/gallery-1.jpg",
      "/images/properties/southern-marina-puteri-harbour/gallery-2.jpg"
    ],
    tourUrl: "https://360vr.my/southernmarina/",
    tourProvider: "generic" as const,
    featured: false,
    type: ["city"],
    coordinates: [103.6558, 1.414] as [number, number],
    developer: "",
    towers: [],
    address: "Puteri Harbour, Johor Bahru",
  },
  {
    id: "ponderosa-regency",
    slug: "ponderosa-regency",
    name: "Ponderosa Regency",
    area: "Johor Bahru",
    district: "Johor Bahru",
    category: "city" as const,
    price: { sgd: 119402, myr: 400000 },
    priceRange: "RM400K+",
    specs: { beds: "1-3", baths: "1-2", size: "450 - 1,200" },
    yield: 6.0,
    rtsDistance: "TBD",
    tenure: "Freehold",
    completionYear: "2029",
    status: "available" as const,
    description: "Ponderosa Regency is an exclusive freehold condominium by AGB, the reputable developer behind Molek Regency. Located in the prestigious Taman Ponderosa neighbourhood, the project offers a low-density living environment with spacious layouts, premium finishing, and excellent workmanship — continuing the developer’s reputation for quality.",
    highlights: [
      "Developed by AGB – same workmanship & quality as Molek Regency",
      "Managed by Knight Frank – world-class property management",
      "Pet-friendly concept – rare in JB, allows pets",
      "Attractive for Airbnb & rental business (pet-allowed advantage)",
      "Prestigious Taman Ponderosa address with low-density living",
      "Excellent access to Tebrau Highway, IKEA, Toppen, AEON Tebrau, Mid Valley Southkey"
    ],
    unitTypes: [],
    image: "/images/properties/ponderosa-regency/hero.jpg",
    images: [
      "/images/properties/ponderosa-regency/hero.jpg",
      "/images/properties/ponderosa-regency/gallery-1.jpg",
      "/images/properties/ponderosa-regency/gallery-2.jpg"
    ],
    tourUrl: "https://www.arsgather.com/360/PONDEROSA%20REGENCY01/",
    tourProvider: "generic" as const,
    featured: false,
    type: ["city"],
    coordinates: [103.7778, 1.516] as [number, number],
    developer: "",
    towers: [],
    address: "Johor Bahru, Johor Bahru",
  },
  {
    id: "paragon-signature-suites-jalan-abdul-samad",
    slug: "paragon-signature-suites-jalan-abdul-samad",
    name: "Paragon Signature Suites Jln Abdul Samad",
    area: "Jalan Abdul Samad",
    district: "Johor Bahru City",
    category: "city" as const,
    price: { sgd: 119402, myr: 400000 },
    priceRange: "RM400K+",
    specs: { beds: "1-3", baths: "1-2", size: "450 - 1,200" },
    yield: 6.0,
    rtsDistance: "TBD",
    tenure: "Freehold",
    completionYear: "2030 Q1",
    status: "available" as const,
    description: "Paragon Signature Suites is a boutique high-rise residence located at Jalan Abdul Samad, offering a peaceful living environment right in the Johor Bahru city centre. With only 484 units, this low-density development provides privacy and exclusivity.",
    highlights: [
      "Strategic location at Jalan Abdul Samad, close to JB CIQ & city centre",
      "Low-density development – only 484 units in total",
      "Larger built-up sizes with 1-Bedroom & 1+1 Bedroom layouts",
      "Hotel-style residence with modern facilities",
      "Peaceful environment, suitable for singles, couples & retirees",
      "Foreigner eligible – attractive entry price from RM4xxK"
    ],
    unitTypes: [],
    image: "/images/properties/paragon-signature-suites-jalan-abdul-samad/hero.jpg",
    images: [
      "/images/properties/paragon-signature-suites-jalan-abdul-samad/hero.jpg",
      "/images/properties/paragon-signature-suites-jalan-abdul-samad/gallery-1.jpg",
      "/images/properties/paragon-signature-suites-jalan-abdul-samad/gallery-2.jpg"
    ],
    tourUrl: "https://360media.com.my/paragon/typeA/",
    tourProvider: "generic" as const,
    featured: false,
    type: ["city"],
    coordinates: [103.7411, 1.4663] as [number, number],
    developer: "",
    towers: [],
    address: "Jalan Abdul Samad, Johor Bahru",
  },
  {
    id: "puteri-cove-residences-puteri-harbour",
    slug: "puteri-cove-residences-puteri-harbour",
    name: "Puteri Cove Residences Puteri Harbour",
    area: "Puteri Harbour",
    district: "Iskandar Puteri",
    category: "city" as const,
    price: { sgd: 149253, myr: 500000 },
    priceRange: "RM500K+",
    specs: { beds: "1-3", baths: "1-2", size: "450 - 1,200" },
    yield: 6.0,
    rtsDistance: "TBD",
    tenure: "Freehold",
    completionYear: "2017",
    status: "available" as const,
    description: "Puteri Cove Residences & Quayside is a freehold, seafront condominium located in the prestigious Puteri Harbour, Iskandar Puteri. Completed in 2017 by Pearl Discovery Development, the project combines exclusive seaview residences with a vibrant waterfront retail promenade known as Quayside.",
    highlights: [
      "Freehold Seafront Condominium – direct marina & sea views",
      "1,054 Units – wide range from suites to penthouses & SOHO/loft layouts",
      "Quayside Retail Promenade – waterfront F&B, shops & lifestyle amenities",
      "Comprehensive Facilities – pools, sky gym, gardens, tennis courts & function halls",
      "Prestigious Puteri Harbour Address – near ferry terminal, yacht marina, international schools & healthcare"
    ],
    unitTypes: [],
    image: "/images/properties/puteri-cove-residences-puteri-harbour/hero.jpg",
    images: [
      "/images/properties/puteri-cove-residences-puteri-harbour/hero.jpg",
      "/images/properties/puteri-cove-residences-puteri-harbour/gallery-1.jpg",
      "/images/properties/puteri-cove-residences-puteri-harbour/gallery-2.jpg"
    ],
    featured: false,
    type: ["city"],
    coordinates: [103.6536, 1.4121] as [number, number],
    developer: "",
    towers: [],
    address: "Puteri Harbour, Johor Bahru",
  },
  {
    id: "the-straits-duo-permas",
    slug: "the-straits-duo-permas",
    name: "The Straits View Duo Permas Jaya",
    area: "Permas Jaya",
    district: "Johor Bahru East",
    category: "city" as const,
    price: { sgd: 0, myr: 0 },
    priceRange: "N/A+",
    specs: { beds: "1-3", baths: "1-2", size: "450 - 1,200" },
    yield: 6.0,
    rtsDistance: "TBD",
    tenure: "Freehold",
    completionYear: "2028",
    status: "available" as const,
    description: "Straits View Duo by BRDB Developments is a freehold residential project strategically located at the core of Permas Jaya , Johor Bahru. Sitting right within the Permas Commercial Hub , the development enjoys unmatched convenience — surrounded by shop houses, restaurants, banks, and the local night market , all within walking distance.",
    highlights: [
      "Located at the most central area of Permas Jaya",
      "Surrounded by shop houses, eateries & night market – all walkable",
      "Freehold development by BRDB – trusted Malaysian developer",
      "1–4 bedroom dual units with practical, modern layouts",
      "Full condominium facilities & 24-hour security",
      "Among the most affordable prices in Johor Bahru city"
    ],
    unitTypes: [],
    image: "/images/properties/the-straits-duo-permas/hero.jpg",
    images: [
      "/images/properties/the-straits-duo-permas/hero.jpg",
      "/images/properties/the-straits-duo-permas/gallery-1.jpg",
      "/images/properties/the-straits-duo-permas/gallery-2.jpg",
      "/images/properties/the-straits-duo-permas/gallery-3.jpg",
      "/images/properties/the-straits-duo-permas/gallery-4.jpg",
      "/images/properties/the-straits-duo-permas/gallery-5.jpg"
    ],
    featured: false,
    type: ["city"],
    coordinates: [103.8107, 1.4995] as [number, number],
    developer: "",
    towers: [],
    address: "Permas Jaya, Johor Bahru",
  },
  {
    id: "exsim",
    slug: "exsim",
    name: "Exsim Causewayz Bukit Chagar",
    area: "Johor Bahru",
    district: "Johor Bahru",
    category: "city" as const,
    price: { sgd: 149253, myr: 500000 },
    priceRange: "RM500k+",
    specs: { beds: "1-3", baths: "1-2", size: "450 - 1,200" },
    yield: 6.0,
    rtsDistance: "TBD",
    tenure: "Freehold",
    completionYear: "2030 Q1",
    status: "available" as const,
    description: "Exsim Causewayz CIQ is an upcoming landmark mixed-use development by Exsim Group, strategically located next to Johor Bahru CIQ and the future RTS Link Station. Positioned as one of the closest residential and commercial projects to Singapore, it is set to redefine city living with modern serviced apartments, retail, and lifestyle components all integrated into one development.",
    highlights: [
      "Developed by Exsim Group – award-winning developer with strong track record",
      "Next to Johor Bahru CIQ & RTS – seamless connection to Singapore",
      "Mixed-use concept with residential, retail & lifestyle offerings",
      "Prime address with strong rental demand from cross-border commuters",
      "Iconic architecture set to become a new JB landmark",
      "High investment potential – capital appreciation & rental yield"
    ],
    unitTypes: [],
    image: "/images/properties/exsim/hero.jpg",
    images: [
      "/images/properties/exsim/hero.jpg",
      "/images/properties/exsim/gallery-1.jpg",
      "/images/properties/exsim/gallery-2.jpg"
    ],
    tourUrl: "https://360vr.my/exsim/causewayz/",
    tourProvider: "generic" as const,
    featured: false,
    type: ["city"],
    coordinates: [103.7667, 1.4628] as [number, number],
    developer: "",
    towers: [],
    address: "Johor Bahru, Johor Bahru",
  },
  {
    id: "mbw-bay-danga-bay",
    slug: "mbw-bay-danga-bay",
    name: "MBW Bay Danga Bay",
    area: "Danga Bay",
    district: "Johor Bahru Waterfront",
    category: "city" as const,
    price: { sgd: 149253, myr: 500000 },
    priceRange: "RM500K+",
    specs: { beds: "1-3", baths: "1-2", size: "450 - 1,200" },
    yield: 6.0,
    rtsDistance: "TBD",
    tenure: "Freehold",
    completionYear: "2026/29",
    status: "available" as const,
    description: "MBW BAY is a landmark freehold seafront township development in Johor Bahru, developed by MB World Properties / Channel Soft Solutions. Spread over 17.43 acres, this mixed-use flagship project combines residential, retail, and lifestyle offerings, all designed with biophilic architecture in mind—bringing nature, wellness, and sustainability together for modern urban living.",
    highlights: [
      "Freehold Seafront Residences with coastal & skyline views",
      "Flexible layouts from ~495 sqft to ~2,796 sqft – compact units to larger family/dual-key options",
      "30+ resort-style amenities (swimming pool, sky terrace, wellness gardens, etc.)",
      "Retail shops at levels 1 & 2 + market by doorstep for daily convenience",
      "GreenRE certified – built with sustainability & wellness in mind",
      "Roughly 8 km to future RTS / CIQ – great for commuters & cross-border connection"
    ],
    unitTypes: [],
    image: "/images/properties/mbw-bay-danga-bay/hero.jpg",
    images: [
      "/images/properties/mbw-bay-danga-bay/hero.jpg",
      "/images/properties/mbw-bay-danga-bay/gallery-1.jpg",
      "/images/properties/mbw-bay-danga-bay/gallery-2.jpg"
    ],
    featured: false,
    type: ["city"],
    coordinates: [103.7213, 1.4695] as [number, number],
    developer: "",
    towers: [],
    address: "Danga Bay, Johor Bahru",
  },
  {
    id: "country-garden-danga-bay",
    slug: "country-garden-danga-bay",
    name: "Country Garden Danga Bay",
    area: "Danga Bay",
    district: "Johor Bahru Waterfront",
    category: "city" as const,
    price: { sgd: 149253, myr: 500000 },
    priceRange: "RM500K+",
    specs: { beds: "1-3", baths: "1-2", size: "450 - 1,200" },
    yield: 6.0,
    rtsDistance: "TBD",
    tenure: "Freehold",
    completionYear: "2016/17",
    status: "available" as const,
    description: "Country Garden Danga Bay is one of Johor Bahru’s most established freehold integrated developments, combining residential towers, commercial areas, shopping mall, public beach, and lifestyle amenities all in one township. Conveniently located just 6.5km from CIQ, it also provides a dedicated shuttle bus service for seamless connectivity to Singapore.",
    highlights: [
      "Freehold integrated township – residential, commercial, mall & public beach",
      "Only 6.5km to CIQ with dedicated shuttle bus service to Singapore",
      "Completed & ready to move in – what you see is what you get",
      "Attractive pricing & sales packages – unbeatable in JB city",
      "Units with seaview & beautiful sunset views available",
      "Established amenities within the township – lifestyle hub by the waterfront"
    ],
    unitTypes: [],
    image: "/images/properties/country-garden-danga-bay/hero.jpg",
    images: [
      "/images/properties/country-garden-danga-bay/hero.jpg",
      "/images/properties/country-garden-danga-bay/gallery-1.jpg",
      "/images/properties/country-garden-danga-bay/gallery-2.jpg"
    ],
    featured: false,
    type: ["city"],
    coordinates: [103.7245, 1.4644] as [number, number],
    developer: "",
    towers: [],
    address: "Danga Bay, Johor Bahru",
  },
  {
    id: "majestic-gensphere-bukit-chagar",
    slug: "majestic-gensphere-bukit-chagar",
    name: "Majestic Gensphere Bukit Chagar",
    area: "Bukit Chagar",
    district: "Johor Bahru City",
    category: "city" as const,
    price: { sgd: 179104, myr: 600000 },
    priceRange: "RM600K+",
    specs: { beds: "1-3", baths: "1-2", size: "450 - 1,200" },
    yield: 6.0,
    rtsDistance: "TBD",
    tenure: "Freehold",
    completionYear: "2030 Q1",
    status: "available" as const,
    description: "Majestic GenSphere is a boutique high-rise residence located only 440 metres from CIQ Johor Bahru, with a direct link bridge providing seamless access to Singapore. Designed as a premium development, it offers exclusive rooftop facilities, including an infinity pool with panoramic views. With its compact and efficient layouts, Majestic GenSphere remains competitively priced compared to surrounding projects, making it an attractive option for both homeowners and investors.",
    highlights: [
      "Link Bridge to CIQ & R&F Mall – excellent cross-border convenience",
      "Exclusive rooftop facilities with sky infinity pool",
      "Compact layouts, making overall entry price more affordable",
      "Flexible design – selected units can be converted into dual-key"
    ],
    unitTypes: [],
    image: "/images/properties/majestic-gensphere-bukit-chagar/hero.jpg",
    images: [
      "/images/properties/majestic-gensphere-bukit-chagar/hero.jpg",
      "/images/properties/majestic-gensphere-bukit-chagar/gallery-1.jpg",
      "/images/properties/majestic-gensphere-bukit-chagar/gallery-2.jpg"
    ],
    tourUrl: "https://www.7degree.com.my/360VR/GenSphere/",
    tourProvider: "generic" as const,
    featured: false,
    type: ["city"],
    coordinates: [103.7648, 1.4603] as [number, number],
    developer: "",
    towers: [],
    address: "Bukit Chagar, Johor Bahru",
  },
  {
    id: "paragon-calia-danga-bay",
    slug: "paragon-calia-danga-bay",
    name: "Paragon Calia Danga Bay",
    area: "Danga Bay",
    district: "Johor Bahru Waterfront",
    category: "city" as const,
    price: { sgd: 149253, myr: 500000 },
    priceRange: "RM500K+",
    specs: { beds: "1-3", baths: "1-2", size: "450 - 1,200" },
    yield: 6.0,
    rtsDistance: "TBD",
    tenure: "Freehold",
    completionYear: "2029",
    status: "available" as const,
    description: "Paragon Calia Residence is a freehold residential project by Paragon Globe Berhad (PGB), strategically located at Danga Bay, just about 7.5 km from CIQ Johor Bahru. Designed to be affordable yet modern, it offers practical layouts that suit young professionals, first-time homeowners, and especially those working in Singapore who are seeking a lower-budget but well-connected residence.",
    highlights: [
      "Developed by PGB (Paragon Globe Berhad) – reputable local developer",
      "Located at Danga Bay, ~7.5 km from CIQ – convenient for Singapore workers",
      "Affordable entry price – suitable for young buyers & budget-conscious investors",
      "Practical layouts – ideal for first-time homeowners and rental market",
      "Freehold tenure – long-term ownership security"
    ],
    unitTypes: [],
    image: "/images/properties/paragon-calia-danga-bay/hero.jpg",
    images: [
      "/images/properties/paragon-calia-danga-bay/hero.jpg",
      "/images/properties/paragon-calia-danga-bay/gallery-1.jpg",
      "/images/properties/paragon-calia-danga-bay/gallery-2.jpg"
    ],
    featured: false,
    type: ["city"],
    coordinates: [103.7175, 1.4827] as [number, number],
    developer: "",
    towers: [],
    address: "Danga Bay, Johor Bahru",
  },
  {
    id: "nadi-residence-southkey",
    slug: "nadi-residence-southkey",
    name: "Nadi Residence Southkey",
    area: "Southkey",
    district: "Johor Bahru City",
    category: "city" as const,
    price: { sgd: 149253, myr: 500000 },
    priceRange: "RM500K+",
    specs: { beds: "1-3", baths: "1-2", size: "450 - 1,200" },
    yield: 6.0,
    rtsDistance: "TBD",
    tenure: "Leasehold",
    completionYear: "2027",
    status: "available" as const,
    description: "✨ Nadi Residences is a modern high-rise serviced residence located in the prestigious Southkey township, one of Johor Bahru’s most vibrant and well-planned precincts. As part of the integrated Southkey development, it enjoys the advantage of being just a short walking distance to Mid Valley Southkey Mall, the largest lifestyle mall in JB, offering residents unparalleled convenience with shopping, dining, leisure, and entertainment right at their doorstep.",
    highlights: [
      "Walking distance to Mid Valley Southkey Mall for shopping, dining & entertainment",
      "Direct access via EDL Highway for easy connectivity across JB & to Singapore",
      "30-storey low-density dual-tower design for privacy & comfort",
      "Multiple layout types (1-bed to 3-bed) with built-ups between ~649–1,050 sq ft",
      "3-Tier Security, bright & breezy designs with natural ventilation & lighting",
      "Affordable entry price for a prime city residence in Southkey"
    ],
    unitTypes: [],
    image: "/images/properties/nadi-residence-southkey/hero.jpg",
    images: [
      "/images/properties/nadi-residence-southkey/hero.jpg",
      "/images/properties/nadi-residence-southkey/gallery-1.jpg",
      "/images/properties/nadi-residence-southkey/gallery-2.jpg"
    ],
    tourUrl: "https://www.southkey.com.my/nadiresidences/360/",
    tourProvider: "generic" as const,
    featured: false,
    type: ["city"],
    coordinates: [103.7748, 1.5038] as [number, number],
    developer: "",
    towers: [],
    address: "Southkey, Johor Bahru",
  },
  {
    id: "summer-suites-bukit-chagar",
    slug: "summer-suites-bukit-chagar",
    name: "Summer Suites Bukit Chagar",
    area: "Bukit Chagar",
    district: "Johor Bahru City",
    category: "city" as const,
    price: { sgd: 208955, myr: 700000 },
    priceRange: "RM700K+",
    specs: { beds: "1-3", baths: "1-2", size: "450 - 1,200" },
    yield: 6.0,
    rtsDistance: "TBD",
    tenure: "Freehold",
    completionYear: "2029 Q4",
    status: "available" as const,
    description: "Summer Suite Bukit Chagar is a freehold redevelopment project transformed from the former FGJB Food Court, brought to you by Connoisseur Properties, the same reputable developer behind V @ Summerplace. Strategically located within walking distance to Johor Bahru CIQ and the upcoming RTS Link station, this residence offers excellent connectivity for daily commuters to Singapore.",
    highlights: [
      "Prime Location – Walking distance to Johor Bahru CIQ & upcoming RTS Link station",
      "Trusted Developer – By Connoisseur Properties, same developer as V @ Summerplace",
      "Lower Entry Price – Attractive pricing compared to nearby city projects",
      "High Investment Potential – Strong rental demand from Singapore commuters",
      "Practical Layouts – Modern designs with flexible space planning"
    ],
    unitTypes: [],
    image: "/images/properties/summer-suites-bukit-chagar/hero.jpg",
    images: [
      "/images/properties/summer-suites-bukit-chagar/hero.jpg",
      "/images/properties/summer-suites-bukit-chagar/gallery-1.jpg",
      "/images/properties/summer-suites-bukit-chagar/gallery-2.jpg"
    ],
    tourUrl: "https://my.matterport.com/show/?m=pDi9QmhBzvN",
    tourProvider: "generic" as const,
    featured: false,
    type: ["city"],
    coordinates: [103.7677, 1.4618] as [number, number],
    developer: "",
    towers: [],
    address: "Bukit Chagar, Johor Bahru",
  },
];

export function getPropertyBySlug(slug: string): Property | undefined {
  return properties.find((p) => p.slug === slug);
}

export function getPropertiesByCategory(category: string): Property[] {
  if (category === 'all') return properties;
  return properties.filter((p) => p.category === category);
}

export function getFeaturedProperties(): Property[] {
  return properties.filter((p) => p.featured);
}

export function getAvailableProperties(): Property[] {
  return properties.filter((p) => p.status !== 'sold-out' && p.status !== 'coming-soon');
}
