// Auto-generated from buy.html — do not edit manually
// Run: python scripts/extract-properties.py

export interface PropertyListing {
  slug: string
  name: string
  city: 'johor-bahru' | 'kuala-lumpur' | 'penang'
  area: string
  status: string
  tenure: string
  image: string
  location: string
  price: string
  distance: string
  feature: string
  badges: string[]
  hidden?: boolean
}

export const propertyListings: PropertyListing[] = [
  {
    slug: 'rf-princess-cove',
    name: "R&F Princess Cove",
    city: 'johor-bahru',
    area: 'bukit-chagar',
    status: 'completed',
    tenure: 'freehold',
    image: "/images/properties/rf-princess-cove-overview/hero.jpg",
    location: "Bukit Chagar",
    price: "From RM350,000",
    distance: "500m to RTS",
    feature: "116-acre mega project",
    badges: ["Completed", "Freehold", "4 Phases"],
    hidden: true,
  },
  {
    slug: 'rf-princess-cove-overview',
    name: "R&F Princess Cove — All Phases",
    city: 'johor-bahru',
    area: 'bukit-chagar',
    status: 'new-launch',
    tenure: 'freehold',
    image: "/images/properties/rf-princess-cove-overview/hero.jpg",
    location: "Tanjung Puteri, Bukit Chagar",
    price: "From RM380,000",
    distance: "1km to CIQ/RTS",
    feature: "116-acre mega project",
    badges: ["All Phases", "Freehold"],
  },
  {
    slug: 'ctc-skyone-bukit-chagar',
    name: "CTC Skyone Bukit Chagar",
    city: 'johor-bahru',
    area: 'bukit-chagar',
    status: 'new-launch',
    tenure: 'freehold',
    image: "/images/properties/ctc-skyone-bukit-chagar/hero.jpg",
    location: "Bukit Chagar",
    price: "From RM500,000",
    distance: "300m to RTS",
    feature: "300m to RTS Link",
    badges: ["New Launch", "Freehold", "Dual-Key"],
  },
  {
    slug: 'majestic-gensphere-bukit-chagar',
    name: "Majestic Gensphere Bukit Chagar",
    city: 'johor-bahru',
    area: 'bukit-chagar',
    status: 'completed',
    tenure: 'freehold',
    image: "/images/properties/majestic-gensphere-bukit-chagar/hero.jpg",
    location: "Bukit Chagar",
    price: "From RM530,000",
    distance: "Bukit Chagar",
    feature: "Completed",
    badges: ["Completed", "Freehold"],
    
  },
  {
    slug: 'exsim-causewayz-bukit-chagar',
    name: "Exsim Causewayz Bukit Chagar",
    city: 'johor-bahru',
    area: 'bukit-chagar',
    status: 'completed',
    tenure: 'freehold',
    image: "https://exsim-causewayzsquare.com/wp-content/uploads/2025/06/Screenshot-2025-06-12-at-4.29.53-PM-min.png",
    location: "Bukit Chagar",
    price: "Price on Request",
    distance: "Bukit Chagar",
    feature: "Completed",
    badges: ["Completed", "Freehold"],
    hidden: true,
  },
  {
    slug: 'summer-suites-bukit-chagar',
    name: "Summer Suites Bukit Chagar",
    city: 'johor-bahru',
    area: 'bukit-chagar',
    status: 'new-launch',
    tenure: 'freehold',
    image: "/images/properties/summer-suites-bukit-chagar/hero.jpg",
    location: "Bukit Chagar",
    price: "From RM600k",
    distance: "Bukit Chagar",
    feature: "New Launch",
    badges: ["New Launch", "Freehold"],
    
  },
  {
    slug: 'the-arden-one-bukit-senyum',
    name: "The Arden One Bukit Senyum",
    city: 'johor-bahru',
    area: 'bukit-senyum',
    status: 'completed',
    tenure: 'freehold',
    image: "/images/properties/the-arden-one-bukit-senyum/hero.jpg",
    location: "Bukit Senyum",
    price: "From RM1mil",
    distance: "Bukit Senyum",
    feature: "Completed",
    badges: ["Completed", "Freehold"],
    
  },
  {
    slug: 'the-astaka-one-bukit-senyum',
    name: "The Astaka One Bukit Senyum",
    city: 'johor-bahru',
    area: 'bukit-senyum',
    status: 'completed',
    tenure: 'freehold',
    image: "/images/properties/the-astaka-one-bukit-senyum/hero.jpg",
    location: "Bukit Senyum",
    price: "From RM2.5mil",
    distance: "Bukit Senyum",
    feature: "Completed",
    badges: ["Completed", "Freehold"],
    
  },
  {
    slug: 'paragon-signature-suites-jln-abdul-samad',
    name: "Paragon Signature Suites Jln Abdul Samad",
    city: 'johor-bahru',
    area: 'jln-abdul-samad',
    status: 'completed',
    tenure: 'freehold',
    image: "https://paragonsignaturesuites.com.my/wp-content/uploads/2024/09/home-bk1-scaled.webp",
    location: "Jln Abdul Samad",
    price: "From RM450k",
    distance: "Jln Abdul Samad",
    feature: "Completed",
    badges: ["Completed", "Freehold"],
    hidden: true,
  },
  {
    slug: 'm-grand-minori-taman-pelangi',
    name: "M Grand Minori Taman Pelangi",
    city: 'johor-bahru',
    area: 'taman-pelangi',
    status: 'completed',
    tenure: 'freehold',
    image: "/images/properties/m-grand-minori-taman-pelangi/hero.jpg",
    location: "Taman Pelangi",
    price: "Price on Request",
    distance: "Taman Pelangi",
    feature: "Completed",
    badges: ["Completed", "Freehold"],
    
  },
  {
    slug: 'maxim-the-address-taman-pelangi',
    name: "Maxim The Address Taman Pelangi",
    city: 'johor-bahru',
    area: 'taman-pelangi',
    status: 'completed',
    tenure: 'freehold',
    image: "/images/properties/maxim-the-address-taman-pelangi/hero.jpg",
    location: "Taman Pelangi",
    price: "Price on Request",
    distance: "Taman Pelangi",
    feature: "Completed",
    badges: ["Completed", "Freehold"],
    
  },
  {
    slug: 'skypark-kepler-lido-waterfront-boulevard',
    name: "Skypark Kepler Lido Waterfront Boulevard",
    city: 'johor-bahru',
    area: 'lido-waterfront-boulevard',
    status: 'new-launch',
    tenure: 'freehold',
    image: "/images/properties/skypark-kepler-lido-waterfront-boulevard/hero.jpg",
    location: "Lido Waterfront Boulevard",
    price: "Price on Request",
    distance: "Lido Waterfront Boulevard",
    feature: "New Launch",
    badges: ["New Launch", "Freehold"],
    
  },
  {
    slug: 'sunway-majestic-ara-soho',
    name: "Sunway Majestic Ara SOHO",
    city: 'johor-bahru',
    area: 'jalan-yahya-awal',
    status: 'new-launch',
    tenure: 'freehold',
    image: "https://assets.sunwayproperty.com/2025/07/05_SunwayMajectic_OverallFacade_HR.jpg",
    location: "Jalan Yahya Awal",
    price: "Price on Request",
    distance: "Jalan Yahya Awal",
    feature: "New Launch",
    badges: ["New Launch", "Freehold"],
    hidden: true,
  },
  {
    slug: 'skyline-one-sentosa-taman-sentosa',
    name: "Skyline One Sentosa Taman Sentosa",
    city: 'johor-bahru',
    area: 'taman-sentosa',
    status: 'completed',
    tenure: 'freehold',
    image: "/images/properties/skyline-one-sentosa-taman-sentosa/hero.jpg",
    location: "Taman Sentosa",
    price: "Price on Request",
    distance: "Taman Sentosa",
    feature: "Completed",
    badges: ["Completed", "Freehold"],
    
  },
  {
    slug: 'paragon-gateway-taman-suria',
    name: "Paragon Gateway Taman Suria",
    city: 'johor-bahru',
    area: 'taman-suria',
    status: 'new-launch',
    tenure: 'freehold',
    image: "/images/properties/paragon-gateway-taman-suria/hero.jpg",
    location: "Taman Suria",
    price: "Price on Request",
    distance: "Taman Suria",
    feature: "New Launch",
    badges: ["New Launch", "Freehold"],
    
  },
  {
    slug: 'country-garden-danga-bay',
    name: "Country Garden Danga Bay",
    city: 'johor-bahru',
    area: 'danga-bay',
    status: 'completed',
    tenure: 'freehold',
    image: "/images/properties/country-garden-danga-bay/hero.jpg",
    location: "Danga Bay",
    price: "Price on Request",
    distance: "Danga Bay",
    feature: "Completed",
    badges: ["Completed", "Freehold"],
    
  },
  {
    slug: 'mbw-bay-danga-bay',
    name: "MBW Bay Danga Bay",
    city: 'johor-bahru',
    area: 'danga-bay',
    status: 'new-launch',
    tenure: 'freehold',
    image: "/images/properties/mbw-bay-danga-bay/hero.jpg",
    location: "Danga Bay",
    price: "Price on Request",
    distance: "Danga Bay",
    feature: "New Launch",
    badges: ["New Launch", "Freehold"],
    
  },
  {
    slug: 'paragon-calia-danga-bay',
    name: "Paragon Calia Danga Bay",
    city: 'johor-bahru',
    area: 'danga-bay',
    status: 'new-launch',
    tenure: 'freehold',
    image: "/images/properties/paragon-calia-danga-bay/hero.jpg",
    location: "Danga Bay",
    price: "Price on Request",
    distance: "Danga Bay",
    feature: "New Launch",
    badges: ["New Launch", "Freehold"],
    
  },
  {
    slug: 'parkland-by-the-river-permas',
    name: "Parkland by the river Permas",
    city: 'johor-bahru',
    area: 'permas-jaya',
    status: 'new-launch',
    tenure: 'freehold',
    image: "/images/properties/parkland-by-the-river-permas/hero.jpg",
    location: "Permas Jaya",
    price: "Price on Request",
    distance: "Permas Jaya",
    feature: "New Launch",
    badges: ["New Launch", "Freehold"],
    
  },
  {
    slug: 'the-straits-view-duo-permas-jaya',
    name: "The Straits View Duo Permas Jaya",
    city: 'johor-bahru',
    area: 'permas-jaya',
    status: 'new-launch',
    tenure: 'freehold',
    image: "https://straitsviewduo.com/wp-content/uploads/2025/08/Untitled-design-22.jpg",
    location: "Permas Jaya",
    price: "Price on Request",
    distance: "Permas Jaya",
    feature: "New Launch",
    badges: ["New Launch", "Freehold"],
    hidden: true,
  },
  {
    slug: 'ponderosa-regency',
    name: "Ponderosa Regency",
    city: 'johor-bahru',
    area: 'taman-ponderosa',
    status: 'new-launch',
    tenure: 'freehold',
    image: "/images/properties/ponderosa-regency/hero.jpg",
    location: "Taman Ponderosa",
    price: "Price on Request",
    distance: "Taman Ponderosa",
    feature: "New Launch",
    badges: ["New Launch", "Freehold"],
    
  },
  {
    slug: 'elysia-park-medini',
    name: "Elysia Park Medini",
    city: 'johor-bahru',
    area: 'medini-iskandar-puteri',
    status: 'completed',
    tenure: 'leasehold',
    image: "/images/properties/elysia-park-medini/hero.jpg",
    location: "Medini Iskandar Puteri",
    price: "Price on Request",
    distance: "Medini Iskandar Puteri",
    feature: "Completed",
    badges: ["Completed", "Leasehold"],
    
  },
  {
    slug: 'the-m-macrolink-medini',
    name: "The M Macrolink Medini",
    city: 'johor-bahru',
    area: 'medini-iskandar-puteri',
    status: 'completed',
    tenure: 'leasehold',
    image: "/images/properties/the-m-macrolink-medini/hero.jpg",
    location: "Medini Iskandar Puteri",
    price: "Price on Request",
    distance: "Medini Iskandar Puteri",
    feature: "Completed",
    badges: ["Completed", "Leasehold"],
    
  },
  {
    slug: 'southern-marina-puteri-harbour',
    name: "Southern Marina Puteri Harbour",
    city: 'johor-bahru',
    area: 'puteri-harbour',
    status: 'completed',
    tenure: 'freehold',
    image: "/images/properties/southern-marina-puteri-harbour/hero.jpg",
    location: "Puteri Harbour",
    price: "Price on Request",
    distance: "Puteri Harbour",
    feature: "Completed",
    badges: ["Completed", "Freehold"],
    
  },
  {
    slug: 'puteri-cove-residences-puteri-harbour',
    name: "Puteri Cove Residences Puteri Harbour",
    city: 'johor-bahru',
    area: 'puteri-harbour',
    status: 'completed',
    tenure: 'freehold',
    image: "/images/properties/puteri-cove-residences-puteri-harbour/hero.jpg",
    location: "Puteri Harbour",
    price: "Price on Request",
    distance: "Puteri Harbour",
    feature: "Completed",
    badges: ["Completed", "Freehold"],
    
  },
  {
    slug: 'nadi-residence-southkey',
    name: "Nadi Residence Southkey",
    city: 'johor-bahru',
    area: 'southkey',
    status: 'new-launch',
    tenure: 'leasehold',
    image: "/images/properties/nadi-residence-southkey/hero.jpg",
    location: "Southkey",
    price: "Price on Request",
    distance: "Southkey",
    feature: "New Launch",
    badges: ["New Launch", "Leasehold"],
    
  },
  {
    slug: 'suria-hill-iskandar-puteri',
    name: "Suria Hill Iskandar Puteri",
    city: 'johor-bahru',
    area: 'iskandar-puteri',
    status: 'new-launch',
    tenure: 'freehold',
    image: "https://www.suriahills.com.my/data/editor/home/banner.png",
    location: "Iskandar Puteri",
    price: "Price on Request",
    distance: "Iskandar Puteri",
    feature: "New Launch",
    badges: ["New Launch", "Freehold"],
    hidden: true,
  },
  {
    slug: 'nigella-park-forest-city-sfz',
    name: "Nigella Park Forest City (SFZ)",
    city: 'johor-bahru',
    area: 'forest-city-iskandar-puteri',
    status: 'completed',
    tenure: 'freehold',
    image: "/images/properties/nigella-park-forest-city-sfz/hero.jpg",
    location: "Forest City Iskandar Puteri",
    price: "Price on Request",
    distance: "Forest City Iskandar Puteri",
    feature: "Completed",
    badges: ["Completed", "Freehold"],
    
  },
  {
    slug: 'golf-villa-forest-city-sfz',
    name: "Golf Villa Forest City (SFZ)",
    city: 'johor-bahru',
    area: 'forest-city-iskandar-puteri',
    status: 'completed',
    tenure: 'freehold',
    image: "/images/properties/golf-villa-forest-city-sfz/hero.jpg",
    location: "Forest City Iskandar Puteri",
    price: "Price on Request",
    distance: "Forest City Iskandar Puteri",
    feature: "Completed",
    badges: ["Completed", "Freehold"],
    
  },
  {
    slug: 'avenue-mbw-city',
    name: "Avenue MBW City",
    city: 'johor-bahru',
    area: 'mbw-city',
    status: 'completed',
    tenure: 'leasehold',
    image: "/images/properties/avenue-mbw-city/hero.jpg",
    location: "MBW City",
    price: "Price on Request",
    distance: "MBW City",
    feature: "Completed",
    badges: ["Completed", "Leasehold"],
    
  },
  {
    slug: 'veranda-mbw-city',
    name: "Veranda MBW City",
    city: 'johor-bahru',
    area: 'mbw-city',
    status: 'completed',
    tenure: 'leasehold',
    image: "/images/properties/veranda-mbw-city/hero.jpg",
    location: "MBW City",
    price: "Price on Request",
    distance: "MBW City",
    feature: "Completed",
    badges: ["Completed", "Leasehold"],
    
  },
  {
    slug: 'trellis-mbw-city',
    name: "Trellis MBW City",
    city: 'johor-bahru',
    area: 'mbw-city',
    status: 'completed',
    tenure: 'leasehold',
    image: "/images/properties/trellis-mbw-city/hero.jpg",
    location: "MBW City",
    price: "Price on Request",
    distance: "MBW City",
    feature: "Completed",
    badges: ["Completed", "Leasehold"],
    
  },
  {
    slug: 'marina-residence-bayu-puteri',
    name: "Marina Residence Bayu Puteri",
    city: 'johor-bahru',
    area: 'bayu-puteri',
    status: 'completed',
    tenure: 'leasehold',
    image: "/images/properties/marina-residence-bayu-puteri/hero.jpg",
    location: "Bayu Puteri",
    price: "Price on Request",
    distance: "Bayu Puteri",
    feature: "Completed",
    badges: ["Completed", "Leasehold"],
    
  },
  {
    slug: 'central-park-country-garden',
    name: "Central Park Country Garden",
    city: 'johor-bahru',
    area: 'country-garden',
    status: 'completed',
    tenure: 'leasehold',
    image: "https://dangabaycondo.com/assets/images/custom/header_bg.jpg",
    location: "Country Garden",
    price: "Price on Request",
    distance: "Country Garden",
    feature: "Completed",
    badges: ["Completed", "Leasehold"],
    hidden: true,
  },
  {
    slug: 'ascent-park-iskandar-puteri',
    name: "Ascent Park Iskandar Puteri",
    city: 'johor-bahru',
    area: 'iskandar-puteri',
    status: 'completed',
    tenure: 'leasehold',
    image: "/images/properties/ascent-park-iskandar-puteri/hero.jpg",
    location: "Iskandar Puteri",
    price: "Price on Request",
    distance: "Iskandar Puteri",
    feature: "Completed",
    badges: ["Completed", "Leasehold"],
    
  },
  {
    slug: 'carnelian-tower-forest-city-sfz',
    name: "Carnelian Tower Forest City (SFZ)",
    city: 'johor-bahru',
    area: 'forest-city',
    status: 'completed',
    tenure: 'leasehold',
    image: "/images/properties/carnelian-tower-forest-city-sfz/hero.jpg",
    location: "Forest City",
    price: "Price on Request",
    distance: "Forest City",
    feature: "Completed",
    badges: ["Completed", "Leasehold"],
    
  },
  {
    slug: 'meridin-east',
    name: "Meridin East",
    city: 'johor-bahru',
    area: 'pasir-gudang',
    status: 'completed',
    tenure: 'leasehold',
    image: "/images/properties/meridin-east/hero.jpg",
    location: "Pasir Gudang",
    price: "Price on Request",
    distance: "Pasir Gudang",
    feature: "Completed",
    badges: ["Completed", "Leasehold"],
    
  },
  {
    slug: 'senibong-kews',
    name: "Senibong Kews",
    city: 'johor-bahru',
    area: 'senibong-cove',
    status: 'completed',
    tenure: 'leasehold',
    image: "/images/properties/senibong-kews/hero.jpg",
    location: "Senibong Cove",
    price: "Price on Request",
    distance: "Senibong Cove",
    feature: "Completed",
    badges: ["Completed", "Leasehold"],
    
  },
  {
    slug: 'topaz-crest-austin',
    name: "Topaz Crest Austin",
    city: 'johor-bahru',
    area: 'crest-austin',
    status: 'completed',
    tenure: 'leasehold',
    image: "/images/properties/topaz-crest-austin/hero.jpg",
    location: "Crest Austin",
    price: "Price on Request",
    distance: "Crest Austin",
    feature: "Completed",
    badges: ["Completed", "Leasehold"],
    
  },
  {
    slug: 'bayou-residences-leisure-farm',
    name: "Bayou Residences Leisure Farm",
    city: 'johor-bahru',
    area: 'leisure-farm',
    status: 'completed',
    tenure: 'leasehold',
    image: "/images/properties/bayou-residences-leisure-farm/hero.jpg",
    location: "Leisure Farm",
    price: "Price on Request",
    distance: "Leisure Farm",
    feature: "Completed",
    badges: ["Completed", "Leasehold"],
    
  },
  {
    slug: 'daya-1-residences-taman-daya',
    name: "Daya 1 Residences Taman Daya",
    city: 'johor-bahru',
    area: 'taman-daya',
    status: 'completed',
    tenure: 'leasehold',
    image: "/images/properties/daya-1-residences-taman-daya/hero.jpg",
    location: "Taman Daya",
    price: "Price on Request",
    distance: "Taman Daya",
    feature: "Completed",
    badges: ["Completed", "Leasehold"],
    
  },
  {
    slug: 'd-secret-garden-2-taman-kempas-indah',
    name: "D Secret Garden 2 Taman Kempas Indah",
    city: 'johor-bahru',
    area: 'taman-kempas-indah',
    status: 'completed',
    tenure: 'leasehold',
    image: "/images/properties/d-secret-garden-2-taman-kempas-indah/hero.jpg",
    location: "Taman Kempas Indah",
    price: "Price on Request",
    distance: "Taman Kempas Indah",
    feature: "Completed",
    badges: ["Completed", "Leasehold"],
    
  },
  {
    slug: 'lanna-eco-tropics',
    name: "Lanna Eco Tropics",
    city: 'johor-bahru',
    area: 'eco-tropics-pasir-gudang',
    status: 'completed',
    tenure: 'leasehold',
    image: "https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?w=800&h=600&fit=crop",
    location: "Eco Tropics Pasir Gudang",
    price: "Price on Request",
    distance: "Eco Tropics Pasir Gudang",
    feature: "Completed",
    badges: ["Completed", "Leasehold"],
    hidden: true,
  },
  {
    slug: 'bee-development-nusajaya',
    name: "Bee Development Nusajaya",
    city: 'johor-bahru',
    area: 'nusajaya',
    status: 'completed',
    tenure: 'leasehold',
    image: "/images/properties/bee-development-nusajaya/hero.jpg",
    location: "Nusajaya",
    price: "Price on Request",
    distance: "Nusajaya",
    feature: "Completed",
    badges: ["Completed", "Leasehold"],
    
  },
  {
    slug: 'fraser-heights-gelang-patah',
    name: "Fraser Heights Gelang Patah",
    city: 'johor-bahru',
    area: 'gelang-patah',
    status: 'completed',
    tenure: 'leasehold',
    image: "/images/properties/fraser-heights-gelang-patah/hero.jpg",
    location: "Gelang Patah",
    price: "Price on Request",
    distance: "Gelang Patah",
    feature: "Completed",
    badges: ["Completed", "Leasehold"],
    
  },
  {
    slug: 'isola-coast-senibong-cove',
    name: "Isola Coast Senibong Cove",
    city: 'johor-bahru',
    area: 'senibong-cove',
    status: 'completed',
    tenure: 'leasehold',
    image: "/images/properties/isola-coast-senibong-cove/hero.jpg",
    location: "Senibong Cove",
    price: "Price on Request",
    distance: "Senibong Cove",
    feature: "Completed",
    badges: ["Completed", "Leasehold"],
    
  },
  {
    slug: 'kl-east-east-61',
    name: "KL East : East 61",
    city: 'kuala-lumpur',
    area: 'kl-city-centre',
    status: 'new-launch',
    tenure: 'freehold',
    image: "https://my1-cdn.pgimgs.com/project-listing-project/60629533/PLPHO.286873510.V800/KL-East-East-61-KL-City-Centre-Malaysia.jpg",
    location: "KL City Centre, Kuala Lumpur",
    price: "Price on Request",
    distance: "KL City Centre",
    feature: "Terraced House",
    badges: ["New Launch", "Freehold"],
    hidden: true,
  },
  {
    slug: 'kl-east-the-reya',
    name: "KL East : The Reya",
    city: 'kuala-lumpur',
    area: 'kl-city-centre',
    status: 'new-launch',
    tenure: 'freehold',
    image: "https://images.unsplash.com/photo-1596422846543-75c6fc197f07?w=600&h=400&fit=crop",
    location: "KL City Centre, Kuala Lumpur",
    price: "From RM899,000",
    distance: "KL City Centre",
    feature: "Completion 2029",
    badges: ["New Launch", "Freehold"],
    hidden: true,
  },
  {
    slug: 'psv-2-residences',
    name: "PSV 2 Residences",
    city: 'kuala-lumpur',
    area: 'bandar-tasik-selatan',
    status: 'new-launch',
    tenure: 'leasehold',
    image: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=600&h=400&fit=crop",
    location: "Bandar Tasik Selatan, Kuala Lumpur",
    price: "From RM512,000",
    distance: "Bandar Tasik Selatan",
    feature: "Completion 2028",
    badges: ["New Launch", "Leasehold"],
    hidden: true,
  },
  {
    slug: 'ekotitiwangsa',
    name: "EkoTitiwangsa",
    city: 'kuala-lumpur',
    area: 'setapak',
    status: 'new-launch',
    tenure: 'freehold',
    image: "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=600&h=400&fit=crop",
    location: "Setapak, Kuala Lumpur",
    price: "From RM413,000",
    distance: "Setapak",
    feature: "Completion 2028",
    badges: ["New Launch", "Freehold"],
    hidden: true,
  },
  {
    slug: 'lsh-sentul-ria',
    name: "LSH Sentul Ria",
    city: 'kuala-lumpur',
    area: 'sentul',
    status: 'new-launch',
    tenure: 'freehold',
    image: "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=600&h=400&fit=crop",
    location: "Sentul, Kuala Lumpur",
    price: "Price on Request",
    distance: "Sentul",
    feature: "Service Residence",
    badges: ["New Launch", "Freehold"],
    hidden: true,
  },
  {
    slug: 'papyrus-north-kiara',
    name: "Papyrus North Kiara",
    city: 'kuala-lumpur',
    area: 'mont-kiara',
    status: 'new-launch',
    tenure: 'freehold',
    image: "https://my1-cdn.pgimgs.com/project-listing-project/40570920/PLPHO.252073513.V800/Papyrus-North-Kiara-Mont-Kiara-Malaysia.jpg",
    location: "Mont Kiara, Kuala Lumpur",
    price: "From RM868,000",
    distance: "Mont Kiara",
    feature: "Completion 2028",
    badges: ["New Launch", "Freehold"],
    hidden: true,
  },
  {
    slug: 'swnk-houze-bbcc',
    name: "SWNK Houze @ BBCC",
    city: 'kuala-lumpur',
    area: 'bukit-bintang',
    status: 'new-launch',
    tenure: 'leasehold',
    image: "https://my1-cdn.pgimgs.com/project-listing-project/40593700/PLPHO.264068316.V800/SWNK-Houze-BBCC-Bukit-Bintang-Malaysia.jpg",
    location: "Bukit Bintang, Kuala Lumpur",
    price: "From RM745,000",
    distance: "Bukit Bintang",
    feature: "Completion 2026",
    badges: ["New Launch", "Leasehold"],
    hidden: true,
  },
  {
    slug: 'm-aurora',
    name: "M Aurora",
    city: 'kuala-lumpur',
    area: 'jalan-klang-lama',
    status: 'new-launch',
    tenure: 'freehold',
    image: "https://images.unsplash.com/photo-1567684014761-b65e2e59b9eb?w=600&h=400&fit=crop",
    location: "Jalan Klang Lama, Kuala Lumpur",
    price: "Price on Request",
    distance: "Jalan Klang Lama",
    feature: "Completion 2027",
    badges: ["New Launch", "Freehold"],
    hidden: true,
  },
  {
    slug: 'parkside-residences-setia-federal-hill',
    name: "Parkside Residences @ Setia Federal Hill",
    city: 'kuala-lumpur',
    area: 'bangsar',
    status: 'new-launch',
    tenure: 'leasehold',
    image: "https://my1-cdn.pgimgs.com/project-listing-project/60400131/PLPHO.274369992.V800/Parkside-Residences-Setia-Federal-Hill-Bangsar-Malaysia.jpg",
    location: "Bangsar, Kuala Lumpur",
    price: "From RM665,000",
    distance: "Bangsar",
    feature: "Completion 2030",
    badges: ["New Launch", "Leasehold"],
    hidden: true,
  },
  {
    slug: 'sunway-cochrane',
    name: "Sunway Cochrane",
    city: 'kuala-lumpur',
    area: 'kl-city-centre',
    status: 'new-launch',
    tenure: 'freehold',
    image: "https://images.unsplash.com/photo-1596422846543-75c6fc197f07?w=600&h=400&fit=crop",
    location: "KL City Centre, Kuala Lumpur",
    price: "Price on Request",
    distance: "KL City Centre",
    feature: "Condominium",
    badges: ["New Launch", "Freehold"],
    hidden: true,
  },
  {
    slug: '9-seputeh',
    name: "9 Seputeh",
    city: 'kuala-lumpur',
    area: 'seputeh',
    status: 'new-launch',
    tenure: 'leasehold',
    image: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=600&h=400&fit=crop",
    location: "Jalan Klang Lama, Kuala Lumpur",
    price: "Price on Request",
    distance: "Seputeh",
    feature: "Condominium",
    badges: ["New Launch", "Leasehold"],
    hidden: true,
  },
  {
    slug: 'skyawani-prima-residences',
    name: "SkyAwani PRIMA Residences",
    city: 'kuala-lumpur',
    area: 'setapak',
    status: 'new-launch',
    tenure: 'leasehold',
    image: "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=600&h=400&fit=crop",
    location: "Setapak, Kuala Lumpur",
    price: "Price on Request",
    distance: "Setapak",
    feature: "Apartment",
    badges: ["New Launch", "Leasehold"],
    hidden: true,
  },
  {
    slug: 'the-maple-residences',
    name: "The Maple Residences",
    city: 'kuala-lumpur',
    area: 'jalan-klang-lama',
    status: 'completed',
    tenure: 'freehold',
    image: "https://my1-cdn.pgimgs.com/project-listing-project/40612174/PLPHO.246040889.V800/The-Maple-Residences-Jalan-Klang-Lama-Old-Klang-Road-Malaysia.jpg",
    location: "Jalan Klang Lama, Kuala Lumpur",
    price: "From RM835,000",
    distance: "Jalan Klang Lama",
    feature: "Completed 2025",
    badges: ["Completed", "Freehold"],
    hidden: true,
  },
  {
    slug: 'lsh-segar',
    name: "LSH Segar",
    city: 'kuala-lumpur',
    area: 'cheras',
    status: 'new-launch',
    tenure: 'leasehold',
    image: "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=600&h=400&fit=crop",
    location: "Cheras, Kuala Lumpur",
    price: "From RM567,000",
    distance: "Cheras",
    feature: "Completion 2026",
    badges: ["New Launch", "Leasehold"],
    hidden: true,
  },
  {
    slug: 'tuan-straits-residency',
    name: "Tuan Straits Residency",
    city: 'kuala-lumpur',
    area: 'desa-petaling',
    status: 'new-launch',
    tenure: 'leasehold',
    image: "https://my1-cdn.pgimgs.com/project-listing-project/60628859/PLPHO.286396875.V800/Tuan-Straits-Residency-Desa-Petaling-Malaysia.jpg",
    location: "Desa Petaling, Kuala Lumpur",
    price: "Price on Request",
    distance: "Desa Petaling",
    feature: "Completion 2030",
    badges: ["New Launch", "Leasehold"],
    hidden: true,
  },
  {
    slug: 'kl48',
    name: "KL48",
    city: 'kuala-lumpur',
    area: 'kl-city-centre',
    status: 'new-launch',
    tenure: 'freehold',
    image: "https://images.unsplash.com/photo-1567684014761-b65e2e59b9eb?w=600&h=400&fit=crop",
    location: "KL City Centre, Kuala Lumpur",
    price: "Price on Request",
    distance: "KL City Centre",
    feature: "Condominium",
    badges: ["New Launch", "Freehold"],
    hidden: true,
  },
  {
    slug: 'm-nova',
    name: "M Nova",
    city: 'kuala-lumpur',
    area: 'kepong',
    status: 'new-launch',
    tenure: 'leasehold',
    image: "https://my1-cdn.pgimgs.com/project-listing-project/34334462/PLPHO.193971438.V800/M-Nova-Kepong-Malaysia.jpg",
    location: "Kepong, Kuala Lumpur",
    price: "Price on Request",
    distance: "Kepong",
    feature: "Completion 2028",
    badges: ["New Launch", "Leasehold"],
    hidden: true,
  },
  {
    slug: 'jrayon-residences',
    name: "J.Rayon Residences",
    city: 'kuala-lumpur',
    area: 'seputeh',
    status: 'new-launch',
    tenure: 'leasehold',
    image: "https://images.unsplash.com/photo-1596422846543-75c6fc197f07?w=600&h=400&fit=crop",
    location: "Seputeh, Kuala Lumpur",
    price: "Price on Request",
    distance: "Seputeh",
    feature: "Apartment",
    badges: ["New Launch", "Leasehold"],
    hidden: true,
  },
  {
    slug: 'royal-garden-sri-putramas-4',
    name: "Royal Garden @ Sri Putramas 4",
    city: 'kuala-lumpur',
    area: 'kl-city-centre',
    status: 'new-launch',
    tenure: 'freehold',
    image: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=600&h=400&fit=crop",
    location: "Kuala Lumpur",
    price: "Price on Request",
    distance: "Kuala Lumpur",
    feature: "Condominium",
    badges: ["New Launch", "Freehold"],
    hidden: true,
  },
  {
    slug: 'm-azura',
    name: "M Azura",
    city: 'kuala-lumpur',
    area: 'setapak',
    status: 'new-launch',
    tenure: 'leasehold',
    image: "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=600&h=400&fit=crop",
    location: "Setapak, Kuala Lumpur",
    price: "Price on Request",
    distance: "Setapak",
    feature: "Completion 2028",
    badges: ["New Launch", "Leasehold"],
    hidden: true,
  },
  {
    slug: 'the-nobel-healthcare-park-kl-wellness-city',
    name: "The Nobel Healthcare Park, KL Wellness City",
    city: 'kuala-lumpur',
    area: 'bukit-jalil',
    status: 'new-launch',
    tenure: 'leasehold',
    image: "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=600&h=400&fit=crop",
    location: "Bukit Jalil, Kuala Lumpur",
    price: "From RM414,000",
    distance: "Bukit Jalil",
    feature: "Completion 2026",
    badges: ["New Launch", "Leasehold"],
    hidden: true,
  },
  {
    slug: 'm-aspira',
    name: "M Aspira",
    city: 'kuala-lumpur',
    area: 'taman-desa',
    status: 'new-launch',
    tenure: 'leasehold',
    image: "https://images.unsplash.com/photo-1567684014761-b65e2e59b9eb?w=600&h=400&fit=crop",
    location: "Taman Desa, Kuala Lumpur",
    price: "From RM452,000",
    distance: "Taman Desa",
    feature: "Service Residence",
    badges: ["New Launch", "Leasehold"],
    hidden: true,
  },
  {
    slug: 'bamboo-hills-residences',
    name: "Bamboo Hills Residences",
    city: 'kuala-lumpur',
    area: 'segambut',
    status: 'new-launch',
    tenure: 'freehold',
    image: "https://images.unsplash.com/photo-1596422846543-75c6fc197f07?w=600&h=400&fit=crop",
    location: "Segambut, Kuala Lumpur",
    price: "From RM490,000",
    distance: "Segambut",
    feature: "Completion 2028",
    badges: ["New Launch", "Freehold"],
    hidden: true,
  },
  {
    slug: 'radium-arena-old-klang-road',
    name: "Radium Arena @ Old Klang Road",
    city: 'kuala-lumpur',
    area: 'jalan-klang-lama',
    status: 'new-launch',
    tenure: 'freehold',
    image: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=600&h=400&fit=crop",
    location: "Jalan Klang Lama, Kuala Lumpur",
    price: "From RM410,000",
    distance: "Jalan Klang Lama",
    feature: "Completion 2028",
    badges: ["New Launch", "Freehold"],
    hidden: true,
  },
  {
    slug: 'the-conlay',
    name: "The Conlay",
    city: 'kuala-lumpur',
    area: 'kl-city-centre',
    status: 'completed',
    tenure: 'freehold',
    image: "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=600&h=400&fit=crop",
    location: "KL City Centre, Kuala Lumpur",
    price: "From RM1,552,000",
    distance: "KL City Centre",
    feature: "Completed 2025",
    badges: ["Completed", "Freehold"],
    hidden: true,
  },
  {
    slug: 'chancery-ampang-hybrid-soho',
    name: "Chancery Ampang - Hybrid SOHO",
    city: 'kuala-lumpur',
    area: 'kl-city-centre',
    status: 'new-launch',
    tenure: 'freehold',
    image: "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=600&h=400&fit=crop",
    location: "KL City Centre, Kuala Lumpur",
    price: "From RM422,000",
    distance: "KL City Centre",
    feature: "Completion 2027",
    badges: ["New Launch", "Freehold"],
    hidden: true,
  },
  {
    slug: 'aetas-seputeh',
    name: "Aetas Seputeh",
    city: 'kuala-lumpur',
    area: 'seputeh',
    status: 'new-launch',
    tenure: 'freehold',
    image: "https://images.unsplash.com/photo-1567684014761-b65e2e59b9eb?w=600&h=400&fit=crop",
    location: "Seputeh, Kuala Lumpur",
    price: "From RM3,285,800",
    distance: "Seputeh",
    feature: "Completion 2028",
    badges: ["New Launch", "Freehold"],
    hidden: true,
  },
  {
    slug: 'tangen-residences',
    name: "Tangen Residences",
    city: 'kuala-lumpur',
    area: 'segambut',
    status: 'new-launch',
    tenure: 'freehold',
    image: "https://images.unsplash.com/photo-1596422846543-75c6fc197f07?w=600&h=400&fit=crop",
    location: "Segambut, Kuala Lumpur",
    price: "From RM659,000",
    distance: "Segambut",
    feature: "Completion 2027",
    badges: ["New Launch", "Freehold"],
    hidden: true,
  },
  {
    slug: 'clouthaus-residences',
    name: "CloutHaus Residences",
    city: 'kuala-lumpur',
    area: 'kl-city-centre',
    status: 'new-launch',
    tenure: 'freehold',
    image: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=600&h=400&fit=crop",
    location: "KL City Centre, Kuala Lumpur",
    price: "From RM1,500,000",
    distance: "KL City Centre",
    feature: "Condominium",
    badges: ["New Launch", "Freehold"],
    hidden: true,
  },
  {
    slug: 'aras-residences',
    name: "Aras Residences",
    city: 'kuala-lumpur',
    area: 'jalan-klang-lama',
    status: 'new-launch',
    tenure: 'freehold',
    image: "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=600&h=400&fit=crop",
    location: "Jalan Klang Lama, Kuala Lumpur",
    price: "From RM599,400",
    distance: "Jalan Klang Lama",
    feature: "Condominium",
    badges: ["New Launch", "Freehold"],
    hidden: true,
  },
  {
    slug: 'the-connaught-one',
    name: "The Connaught One",
    city: 'kuala-lumpur',
    area: 'cheras',
    status: 'new-launch',
    tenure: 'leasehold',
    image: "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=600&h=400&fit=crop",
    location: "Cheras, Kuala Lumpur",
    price: "From RM380,000",
    distance: "Cheras",
    feature: "Completion 2027",
    badges: ["New Launch", "Leasehold"],
    hidden: true,
  },
  {
    slug: 'skyaman-1-residences',
    name: "SkyAman 1 Residences",
    city: 'kuala-lumpur',
    area: 'desa-pandan',
    status: 'new-launch',
    tenure: 'leasehold',
    image: "https://images.unsplash.com/photo-1567684014761-b65e2e59b9eb?w=600&h=400&fit=crop",
    location: "Desa Pandan, Kuala Lumpur",
    price: "Price on Request",
    distance: "Desa Pandan",
    feature: "Apartment",
    badges: ["New Launch", "Leasehold"],
    hidden: true,
  },
  {
    slug: 'levia-residence',
    name: "Levia Residence",
    city: 'kuala-lumpur',
    area: 'cheras',
    status: 'new-launch',
    tenure: 'leasehold',
    image: "https://my1-cdn.pgimgs.com/project-listing-project/43191686/PLPHO.265943167.V800/Levia-Residence-Kuala-Lumpur-Cheras-Malaysia.jpg",
    location: "Cheras, Kuala Lumpur",
    price: "From RM684,000",
    distance: "Cheras",
    feature: "Completion 2027",
    badges: ["New Launch", "Leasehold"],
    hidden: true,
  },
  {
    slug: 'pv-22-residences',
    name: "PV 22 Residences",
    city: 'kuala-lumpur',
    area: 'setapak',
    status: 'new-launch',
    tenure: 'leasehold',
    image: "https://my1-cdn.pgimgs.com/project-listing-project/40623328/PLPHO.238853575.V800/PV-22-Residences-Setapak-Malaysia.jpg",
    location: "Setapak, Kuala Lumpur",
    price: "From RM373,000",
    distance: "Setapak",
    feature: "Completion 2028",
    badges: ["New Launch", "Leasehold"],
    hidden: true,
  },
  {
    slug: 'vox-residence-sentul',
    name: "Vox Residence @ Sentul",
    city: 'kuala-lumpur',
    area: 'sentul',
    status: 'new-launch',
    tenure: 'freehold',
    image: "https://my1-cdn.pgimgs.com/project-listing-project/40601773/PLPHO.248479718.V800/Vox-Residence-Sentul-Sentul-Malaysia.jpg",
    location: "Sentul, Kuala Lumpur",
    price: "From RM523,200",
    distance: "Sentul",
    feature: "Completion 2027",
    badges: ["New Launch", "Freehold"],
    hidden: true,
  },
  {
    slug: 'platinum-melati-residences',
    name: "Platinum Melati Residences",
    city: 'kuala-lumpur',
    area: 'kl-city-centre',
    status: 'new-launch',
    tenure: 'freehold',
    image: "https://images.unsplash.com/photo-1596422846543-75c6fc197f07?w=600&h=400&fit=crop",
    location: "KL City Centre, Kuala Lumpur",
    price: "Price on Request",
    distance: "KL City Centre",
    feature: "Condominium",
    badges: ["New Launch", "Freehold"],
    hidden: true,
  },
  {
    slug: 'pinnacle-bukit-gambier',
    name: "Pinnacle Bukit Gambier",
    city: 'penang',
    area: 'bukit-gambier',
    status: 'new-launch',
    tenure: 'freehold',
    image: "https://images.unsplash.com/photo-1596422846543-75c6fc197f07?w=600&h=400&fit=crop",
    location: "Bukit Gambier, Penang",
    price: "From RM588,800",
    distance: "Bukit Gambier",
    feature: "Completion 2030",
    badges: ["New Launch", "Freehold"],
    hidden: true,
  },
  {
    slug: 'skyworld-pearlmont',
    name: "SkyWorld Pearlmont",
    city: 'penang',
    area: 'seberang-jaya',
    status: 'new-launch',
    tenure: 'freehold',
    image: "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=600&h=400&fit=crop",
    location: "Seberang Jaya, Penang",
    price: "From RM323,000",
    distance: "Seberang Jaya",
    feature: "Completion 2029",
    badges: ["New Launch", "Freehold"],
    hidden: true,
  },
  {
    slug: 'eco-sun-irama',
    name: "Eco Sun - Irama",
    city: 'penang',
    area: 'tun-abdullah',
    status: 'new-launch',
    tenure: 'freehold',
    image: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=600&h=400&fit=crop",
    location: "Jalan Tun Abdullah, Penang",
    price: "From RM477,500",
    distance: "Jalan Tun Abdullah",
    feature: "Completion 2029",
    badges: ["New Launch", "Freehold"],
    hidden: true,
  },
  {
    slug: 'setia-sv2',
    name: "SETIA SV2",
    city: 'penang',
    area: 'george-town',
    status: 'new-launch',
    tenure: 'freehold',
    image: "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=600&h=400&fit=crop",
    location: "George Town, Penang",
    price: "From RM969,000",
    distance: "George Town",
    feature: "Completion 2029",
    badges: ["New Launch", "Freehold"],
    hidden: true,
  },
  {
    slug: 'lightwater-residences',
    name: "Lightwater Residences",
    city: 'penang',
    area: 'gelugor',
    status: 'new-launch',
    tenure: 'freehold',
    image: "https://images.unsplash.com/photo-1567684014761-b65e2e59b9eb?w=600&h=400&fit=crop",
    location: "Gelugor, Penang",
    price: "Price on Request",
    distance: "Gelugor",
    feature: "Completion 2029",
    badges: ["New Launch", "Freehold"],
    hidden: true,
  },
  {
    slug: 'harbour-view-residence',
    name: "Harbour View Residence",
    city: 'penang',
    area: 'bagan-dalam',
    status: 'new-launch',
    tenure: 'freehold',
    image: "https://images.unsplash.com/photo-1596422846543-75c6fc197f07?w=600&h=400&fit=crop",
    location: "Bagan Dalam, Penang",
    price: "From RM416,000",
    distance: "Bagan Dalam",
    feature: "Completion 2029",
    badges: ["New Launch", "Freehold"],
    hidden: true,
  },
  {
    slug: 'eco-sun-everine-collection',
    name: "Eco Sun - Everine Collection",
    city: 'penang',
    area: 'tun-abdullah',
    status: 'new-launch',
    tenure: 'freehold',
    image: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=600&h=400&fit=crop",
    location: "Jalan Tun Abdullah, Penang",
    price: "From RM772,800",
    distance: "Jalan Tun Abdullah",
    feature: "Completion 2028",
    badges: ["New Launch", "Freehold"],
    hidden: true,
  },
  {
    slug: 'ferringhi-residence-2',
    name: "Ferringhi Residence 2",
    city: 'penang',
    area: 'batu-ferringhi',
    status: 'completed',
    tenure: 'freehold',
    image: "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=600&h=400&fit=crop",
    location: "Batu Ferringhi, Penang",
    price: "From RM1,064,800",
    distance: "Batu Ferringhi",
    feature: "Completed 2020",
    badges: ["Completed", "Freehold"],
    hidden: true,
  },
  {
    slug: 'tuan-pavilion',
    name: "Tuan Pavilion",
    city: 'penang',
    area: 'ayer-itam',
    status: 'new-launch',
    tenure: 'freehold',
    image: "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=600&h=400&fit=crop",
    location: "Ayer Itam, Penang",
    price: "Price on Request",
    distance: "Ayer Itam",
    feature: "Condominium",
    badges: ["New Launch", "Freehold"],
    hidden: true,
  },
  {
    slug: 'm-zenni',
    name: "M Zenni",
    city: 'penang',
    area: 'bayan-lepas',
    status: 'new-launch',
    tenure: 'freehold',
    image: "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=600&h=400&fit=crop",
    location: "Bayan Lepas, Penang",
    price: "Price on Request",
    distance: "Bayan Lepas",
    feature: "Service Residence",
    badges: ["New Launch", "Freehold"],
    hidden: true,
  },
]

// ─── Query helpers ───

export function getVisibleListings() {
  return propertyListings.filter(p => !p.hidden)
}

export function getListingsByCity(city: string) {
  return getVisibleListings().filter(p => p.city === city)
}

export function getListingBySlug(slug: string) {
  return propertyListings.find(p => p.slug === slug)
}

export function searchListings(query: string) {
  const q = query.toLowerCase()
  return getVisibleListings().filter(p => p.name.toLowerCase().includes(q))
}

export const areas: Record<string, { value: string; label: string }[]> = {
  'johor-bahru': [
    { value: 'bayu-puteri', label: 'Bayu Puteri' },
    { value: 'bukit-chagar', label: 'Bukit Chagar' },
    { value: 'bukit-senyum', label: 'Bukit Senyum' },
    { value: 'country-garden', label: 'Country Garden' },
    { value: 'crest-austin', label: 'Crest Austin' },
    { value: 'danga-bay', label: 'Danga Bay' },
    { value: 'eco-tropics-pasir-gudang', label: 'Eco Tropics Pasir Gudang' },
    { value: 'forest-city', label: 'Forest City' },
    { value: 'forest-city-iskandar-puteri', label: 'Forest City Iskandar Puteri' },
    { value: 'gelang-patah', label: 'Gelang Patah' },
    { value: 'iskandar-puteri', label: 'Iskandar Puteri' },
    { value: 'jalan-yahya-awal', label: 'Jalan Yahya Awal' },
    { value: 'jln-abdul-samad', label: 'Jln Abdul Samad' },
    { value: 'leisure-farm', label: 'Leisure Farm' },
    { value: 'lido-waterfront-boulevard', label: 'Lido Waterfront Boulevard' },
    { value: 'mbw-city', label: 'Mbw City' },
    { value: 'medini-iskandar-puteri', label: 'Medini Iskandar Puteri' },
    { value: 'nusajaya', label: 'Nusajaya' },
    { value: 'pasir-gudang', label: 'Pasir Gudang' },
    { value: 'permas-jaya', label: 'Permas Jaya' },
    { value: 'puteri-harbour', label: 'Puteri Harbour' },
    { value: 'senibong-cove', label: 'Senibong Cove' },
    { value: 'southkey', label: 'Southkey' },
    { value: 'taman-daya', label: 'Taman Daya' },
    { value: 'taman-kempas-indah', label: 'Taman Kempas Indah' },
    { value: 'taman-pelangi', label: 'Taman Pelangi' },
    { value: 'taman-ponderosa', label: 'Taman Ponderosa' },
    { value: 'taman-sentosa', label: 'Taman Sentosa' },
    { value: 'taman-suria', label: 'Taman Suria' },
  ],
  'kuala-lumpur': [
    { value: 'bandar-tasik-selatan', label: 'Bandar Tasik Selatan' },
    { value: 'bangsar', label: 'Bangsar' },
    { value: 'bukit-bintang', label: 'Bukit Bintang' },
    { value: 'bukit-jalil', label: 'Bukit Jalil' },
    { value: 'cheras', label: 'Cheras' },
    { value: 'desa-pandan', label: 'Desa Pandan' },
    { value: 'desa-petaling', label: 'Desa Petaling' },
    { value: 'jalan-klang-lama', label: 'Jalan Klang Lama' },
    { value: 'kepong', label: 'Kepong' },
    { value: 'kl-city-centre', label: 'Kl City Centre' },
    { value: 'mont-kiara', label: 'Mont Kiara' },
    { value: 'segambut', label: 'Segambut' },
    { value: 'sentul', label: 'Sentul' },
    { value: 'seputeh', label: 'Seputeh' },
    { value: 'setapak', label: 'Setapak' },
    { value: 'taman-desa', label: 'Taman Desa' },
  ],
  'penang': [
    { value: 'ayer-itam', label: 'Ayer Itam' },
    { value: 'bagan-dalam', label: 'Bagan Dalam' },
    { value: 'batu-ferringhi', label: 'Batu Ferringhi' },
    { value: 'bayan-lepas', label: 'Bayan Lepas' },
    { value: 'bukit-gambier', label: 'Bukit Gambier' },
    { value: 'gelugor', label: 'Gelugor' },
    { value: 'george-town', label: 'George Town' },
    { value: 'seberang-jaya', label: 'Seberang Jaya' },
    { value: 'tun-abdullah', label: 'Tun Abdullah' },
  ],
}
