// Auto-generated from buy.html — do not edit manually
// Run: python scripts/extract-properties.py

export interface PropertyListing {
  slug: string
  name: string
  city: 'johor-bahru' | 'kuala-lumpur' | 'penang'
  area: string
  status: string
  tenure: string
  image: string
  location: string
  price: string
  distance: string
  feature: string
  badges: string[]
  hidden?: boolean
}

export const propertyListings: PropertyListing[] = [
  {
    slug: 'rf-princess-cove-overview',
    name: "R&F Princess Cove — All Phases",
    city: 'johor-bahru',
    area: 'bukit-chagar',
    status: 'new-launch',
    tenure: 'freehold',
    image: "/images/properties/rf-princess-cove-overview/hero.jpg",
    location: "Tanjung Puteri, Bukit Chagar",
    price: "From RM380,000",
    distance: "1km to CIQ/RTS",
    feature: "116-acre mega project",
    badges: ["All Phases", "Freehold"],
  },
  {
    slug: 'ctc-skyone-bukit-chagar',
    name: "CTC Skyone Bukit Chagar",
    city: 'johor-bahru',
    area: 'bukit-chagar',
    status: 'new-launch',
    tenure: 'freehold',
    image: "/images/properties/ctc-skyone-bukit-chagar/hero.jpg",
    location: "CIQ",
    price: "RM600K to RM2mil",
    distance: "300m to RTS",
    feature: "300m to RTS Link",
    badges: ["Upcoming", "Freehold", "Foreigner Eligible"],
  },
  {
    slug: 'majestic-gensphere-bukit-chagar',
    name: "Majestic Gensphere Bukit Chagar",
    city: 'johor-bahru',
    area: 'bukit-chagar',
    status: 'completed',
    tenure: 'freehold',
    image: "/images/properties/majestic-gensphere-bukit-chagar/hero.jpg",
    location: "CIQ",
    price: "RM500K to RM960K",
    distance: "Bukit Chagar",
    feature: "Completed",
    badges: ["Upcoming", "Freehold", "Foreigner Eligible"],
    
  },
  {
    slug: 'summer-suites-bukit-chagar',
    name: "Summer Suites Bukit Chagar",
    city: 'johor-bahru',
    area: 'bukit-chagar',
    status: 'new-launch',
    tenure: 'freehold',
    image: "/images/properties/summer-suites-bukit-chagar/hero.jpg",
    location: "CIQ",
    price: "RM600K to Rm900K",
    distance: "Bukit Chagar",
    feature: "New Launch",
    badges: ["Upcoming", "Freehold", "Foreigner Eligible"],
    
  },
  {
    slug: 'the-arden-one-bukit-senyum',
    name: "The Arden One Bukit Senyum",
    city: 'johor-bahru',
    area: 'bukit-senyum',
    status: 'completed',
    tenure: 'freehold',
    image: "/images/properties/the-arden-one-bukit-senyum/hero.jpg",
    location: "One Bukit Senyum",
    price: "RM1mil to RM1.8mil",
    distance: "Bukit Senyum",
    feature: "Completed",
    badges: ["Upcoming", "Freehold", "Foreigner Eligible"],
    
  },
  {
    slug: 'the-astaka-one-bukit-senyum',
    name: "The Astaka One Bukit Senyum",
    city: 'johor-bahru',
    area: 'bukit-senyum',
    status: 'completed',
    tenure: 'freehold',
    image: "/images/properties/the-astaka-one-bukit-senyum/hero.jpg",
    location: "One Bukit Senyum",
    price: "RM2mil to RM3mil",
    distance: "Bukit Senyum",
    feature: "Completed",
    badges: ["Completed", "Freehold", "Foreigner Eligible"],
    
  },
  {
    slug: 'm-grand-minori-taman-pelangi',
    name: "M Grand Minori Taman Pelangi",
    city: 'johor-bahru',
    area: 'taman-pelangi',
    status: 'completed',
    tenure: 'freehold',
    image: "/images/properties/m-grand-minori-taman-pelangi/hero.jpg",
    location: "Taman Pelangi",
    price: "RM400K to RM800K",
    distance: "Taman Pelangi",
    feature: "Completed",
    badges: ["Upcoming", "Freehold", "Foreigner Eligible"],
    
  },
  {
    slug: 'maxim-the-address-taman-pelangi',
    name: "Maxim The Address Taman Pelangi",
    city: 'johor-bahru',
    area: 'taman-pelangi',
    status: 'completed',
    tenure: 'freehold',
    image: "/images/properties/maxim-the-address-taman-pelangi/hero.jpg",
    location: "Taman Pelangi",
    price: "RM400K to RM800K",
    distance: "Taman Pelangi",
    feature: "Completed",
    badges: ["Upcoming", "Freehold", "Foreigner Eligible"],
    
  },
  {
    slug: 'skypark-kepler-lido-waterfront-boulevard',
    name: "Skypark Kepler Lido Waterfront Boulevard",
    city: 'johor-bahru',
    area: 'lido-waterfront-boulevard',
    status: 'new-launch',
    tenure: 'freehold',
    image: "/images/properties/skypark-kepler-lido-waterfront-boulevard/hero.jpg",
    location: "Lido Beach",
    price: "RM580K to RM1.2mil",
    distance: "Lido Waterfront Boulevard",
    feature: "New Launch",
    badges: ["Upcoming", "Freehold", "Foreigner Eligible"],
    
  },
  {
    slug: 'skyline-one-sentosa-taman-sentosa',
    name: "Skyline One Sentosa Taman Sentosa",
    city: 'johor-bahru',
    area: 'taman-sentosa',
    status: 'completed',
    tenure: 'freehold',
    image: "/images/properties/skyline-one-sentosa-taman-sentosa/hero.jpg",
    location: "Taman Sentosa",
    price: "RM400k to RM800K",
    distance: "Taman Sentosa",
    feature: "Completed",
    badges: ["Upcoming", "Freehold", "Foreigner Eligible"],
    
  },
  {
    slug: 'paragon-gateway-taman-suria',
    name: "Paragon Gateway Taman Suria",
    city: 'johor-bahru',
    area: 'taman-suria',
    status: 'new-launch',
    tenure: 'freehold',
    image: "/images/properties/paragon-gateway-taman-suria/hero.jpg",
    location: "Taman Suria",
    price: "RM400K to RM1mil",
    distance: "Taman Suria",
    feature: "New Launch",
    badges: ["Upcoming", "Freehold", "Foreigner Eligible"],
    
  },
  {
    slug: 'country-garden-danga-bay',
    name: "Country Garden Danga Bay",
    city: 'johor-bahru',
    area: 'danga-bay',
    status: 'completed',
    tenure: 'freehold',
    image: "/images/properties/country-garden-danga-bay/hero.jpg",
    location: "Danga Bay",
    price: "RM500k to RM1.3mil",
    distance: "Danga Bay",
    feature: "Completed",
    badges: ["Completed", "Freehold", "Foreigner Eligible"],
    
  },
  {
    slug: 'mbw-bay-danga-bay',
    name: "MBW Bay Danga Bay",
    city: 'johor-bahru',
    area: 'danga-bay',
    status: 'new-launch',
    tenure: 'freehold',
    image: "/images/properties/mbw-bay-danga-bay/hero.jpg",
    location: "Danga Bay",
    price: "RM400k to RM800K",
    distance: "Danga Bay",
    feature: "New Launch",
    badges: ["New Launch", "Freehold", "Foreigner Eligible"],
    
  },
  {
    slug: 'paragon-calia-danga-bay',
    name: "Paragon Calia Danga Bay",
    city: 'johor-bahru',
    area: 'danga-bay',
    status: 'new-launch',
    tenure: 'freehold',
    image: "/images/properties/paragon-calia-danga-bay/hero.jpg",
    location: "Danga Bay",
    price: "RM400K to RM700K",
    distance: "Danga Bay",
    feature: "New Launch",
    badges: ["Upcoming", "Freehold", "Foreigner Eligible"],
    
  },
  {
    slug: 'parkland-by-the-river-permas',
    name: "Parkland by the river Permas",
    city: 'johor-bahru',
    area: 'permas-jaya',
    status: 'new-launch',
    tenure: 'freehold',
    image: "/images/properties/parkland-by-the-river-permas/hero.jpg",
    location: "Taman Permas Jaya",
    price: "RM400K to RM700K",
    distance: "Permas Jaya",
    feature: "New Launch",
    badges: ["Upcoming", "Freehold"],
    
  },
  {
    slug: 'ponderosa-regency',
    name: "Ponderosa Regency",
    city: 'johor-bahru',
    area: 'taman-ponderosa',
    status: 'new-launch',
    tenure: 'freehold',
    image: "/images/properties/ponderosa-regency/hero.jpg",
    location: "Taman Ponderosa",
    price: "RM300K to RM800K",
    distance: "Taman Ponderosa",
    feature: "New Launch",
    badges: ["Upcoming", "Freehold", "Foreigner Eligible"],
    
  },
  {
    slug: 'elysia-park-medini',
    name: "Elysia Park Medini",
    city: 'johor-bahru',
    area: 'medini-iskandar-puteri',
    status: 'completed',
    tenure: 'leasehold',
    image: "/images/properties/elysia-park-medini/hero.jpg",
    location: "Medini",
    price: "Rm400k to RM900k",
    distance: "Medini Iskandar Puteri",
    feature: "Completed",
    badges: ["Leasehold", "Foreigner Eligible"],
    
  },
  {
    slug: 'the-m-macrolink-medini',
    name: "The M Macrolink Medini",
    city: 'johor-bahru',
    area: 'medini-iskandar-puteri',
    status: 'completed',
    tenure: 'leasehold',
    image: "/images/properties/the-m-macrolink-medini/hero.jpg",
    location: "Medini",
    price: "RM400K to RM800K",
    distance: "Medini Iskandar Puteri",
    feature: "Completed",
    badges: ["Completed", "Leasehold", "Foreigner Eligible"],
    
  },
  {
    slug: 'southern-marina-puteri-harbour',
    name: "Southern Marina Puteri Harbour",
    city: 'johor-bahru',
    area: 'puteri-harbour',
    status: 'completed',
    tenure: 'freehold',
    image: "/images/properties/southern-marina-puteri-harbour/hero.jpg",
    location: "Puteri Harbour",
    price: "RM700K to RM2.3mil",
    distance: "Puteri Harbour",
    feature: "Completed",
    badges: ["Completed", "Freehold", "Foreigner Eligible"],
    
  },
  {
    slug: 'puteri-cove-residences-puteri-harbour',
    name: "Puteri Cove Residences Puteri Harbour",
    city: 'johor-bahru',
    area: 'puteri-harbour',
    status: 'completed',
    tenure: 'freehold',
    image: "/images/properties/puteri-cove-residences-puteri-harbour/hero.jpg",
    location: "Puteri Harbour",
    price: "RM800K to RM4mil",
    distance: "Puteri Harbour",
    feature: "Completed",
    badges: ["Completed", "Freehold", "Foreigner Eligible"],
    
  },
  {
    slug: 'nadi-residence-southkey',
    name: "Nadi Residence Southkey",
    city: 'johor-bahru',
    area: 'southkey',
    status: 'new-launch',
    tenure: 'leasehold',
    image: "/images/properties/nadi-residence-southkey/hero.jpg",
    location: "Southkey",
    price: "RM400k to RM600k",
    distance: "Southkey",
    feature: "New Launch",
    badges: ["Upcoming", "Leasehold", "Foreigner Eligible"],
    
  },
  {
    slug: 'nigella-park-forest-city-sfz',
    name: "Nigella Park Forest City (SFZ)",
    city: 'johor-bahru',
    area: 'forest-city-iskandar-puteri',
    status: 'completed',
    tenure: 'freehold',
    image: "/images/properties/nigella-park-forest-city-sfz/hero.jpg",
    location: "Forest City",
    price: "RM4mil to RM8mil",
    distance: "Forest City Iskandar Puteri",
    feature: "Completed",
    badges: ["Completed", "Freehold", "Foreigner Eligible"],
    
  },
  {
    slug: 'golf-villa-forest-city-sfz',
    name: "Golf Villa Forest City (SFZ)",
    city: 'johor-bahru',
    area: 'forest-city-iskandar-puteri',
    status: 'completed',
    tenure: 'freehold',
    image: "/images/properties/golf-villa-forest-city-sfz/hero.jpg",
    location: "Forest City",
    price: "RM1.1mil to RM2mil",
    distance: "Forest City Iskandar Puteri",
    feature: "Completed",
    badges: ["Completed", "Freehold", "Foreigner Eligible"],
    
  },
  {
    slug: 'avenue-mbw-city',
    name: "Avenue MBW City",
    city: 'johor-bahru',
    area: 'mbw-city',
    status: 'completed',
    tenure: 'leasehold',
    image: "/images/properties/avenue-mbw-city/hero.jpg",
    location: "MBW City",
    price: "Price on Request",
    distance: "MBW City",
    feature: "Completed",
    badges: ["Completed", "Leasehold"],
    
  },
  {
    slug: 'veranda-mbw-city',
    name: "Veranda MBW City",
    city: 'johor-bahru',
    area: 'mbw-city',
    status: 'completed',
    tenure: 'leasehold',
    image: "/images/properties/veranda-mbw-city/hero.jpg",
    location: "MBW City",
    price: "Price on Request",
    distance: "MBW City",
    feature: "Completed",
    badges: ["Completed", "Leasehold"],
    
  },
  {
    slug: 'trellis-mbw-city',
    name: "Trellis MBW City",
    city: 'johor-bahru',
    area: 'mbw-city',
    status: 'completed',
    tenure: 'leasehold',
    image: "/images/properties/trellis-mbw-city/hero.jpg",
    location: "MBW City",
    price: "Price on Request",
    distance: "MBW City",
    feature: "Completed",
    badges: ["Completed", "Leasehold"],
    
  },
  {
    slug: 'marina-residence-bayu-puteri',
    name: "Marina Residence Bayu Puteri",
    city: 'johor-bahru',
    area: 'bayu-puteri',
    status: 'completed',
    tenure: 'leasehold',
    image: "/images/properties/marina-residence-bayu-puteri/hero.jpg",
    location: "Taman Bakar Batu",
    price: "RM600K to Rm700K",
    distance: "Bayu Puteri",
    feature: "Completed",
    badges: ["Completed", "Leasehold", "Foreigner Eligible"],
    
  },
  {
    slug: 'ascent-park-iskandar-puteri',
    name: "Ascent Park Iskandar Puteri",
    city: 'johor-bahru',
    area: 'iskandar-puteri',
    status: 'completed',
    tenure: 'freehold',
    image: "/images/properties/ascent-park-iskandar-puteri/hero.jpg",
    location: "Iskandar Puteri",
    price: "RM1mil to RM3mil",
    distance: "Iskandar Puteri",
    feature: "Completed",
    badges: ["Upcoming", "Freehold", "Foreigner Eligible"],
    
  },
  {
    slug: 'carnelian-tower-forest-city-sfz',
    name: "Carnelian Tower Forest City (SFZ)",
    city: 'johor-bahru',
    area: 'forest-city',
    status: 'completed',
    tenure: 'freehold',
    image: "/images/properties/carnelian-tower-forest-city-sfz/hero.jpg",
    location: "Forest City",
    price: "RM500k to RM2mil",
    distance: "Forest City",
    feature: "Completed",
    badges: ["Completed", "Freehold", "Foreigner Eligible"],
    
  },
  {
    slug: 'meridin-east',
    name: "Meridin East",
    city: 'johor-bahru',
    area: 'pasir-gudang',
    status: 'completed',
    tenure: 'freehold',
    image: "/images/properties/meridin-east/hero.jpg",
    location: "Pasir Gudang / Masai",
    price: "RM500k to RM700K",
    distance: "Pasir Gudang",
    feature: "Completed",
    badges: ["Completed", "Freehold"],
    
  },
  {
    slug: 'senibong-kews',
    name: "Senibong Kews",
    city: 'johor-bahru',
    area: 'senibong-cove',
    status: 'completed',
    tenure: 'freehold',
    image: "/images/properties/senibong-kews/hero.jpg",
    location: "Leisure Farm",
    price: "RM1mil to RM3mil",
    distance: "Senibong Cove",
    feature: "Completed",
    badges: ["New Launch", "Freehold", "Foreigner Eligible"],
    
  },
  {
    slug: 'topaz-crest-austin',
    name: "Topaz Crest Austin",
    city: 'johor-bahru',
    area: 'crest-austin',
    status: 'completed',
    tenure: 'freehold',
    image: "/images/properties/topaz-crest-austin/hero.jpg",
    location: "Taman Mount Austin",
    price: "RM300k to RM600K",
    distance: "Crest Austin",
    feature: "Completed",
    badges: ["Upcoming", "Freehold"],
    
  },
  {
    slug: 'bayou-residences-leisure-farm',
    name: "Bayou Residences Leisure Farm",
    city: 'johor-bahru',
    area: 'leisure-farm',
    status: 'completed',
    tenure: 'freehold',
    image: "/images/properties/bayou-residences-leisure-farm/hero.jpg",
    location: "Leisure Farm",
    price: "RM1.8mil to RM2.5mil",
    distance: "Leisure Farm",
    feature: "Completed",
    badges: ["Completed", "Freehold", "Foreigner Eligible"],
    
  },
  {
    slug: 'daya-1-residences-taman-daya',
    name: "Daya 1 Residences Taman Daya",
    city: 'johor-bahru',
    area: 'taman-daya',
    status: 'completed',
    tenure: 'freehold',
    image: "/images/properties/daya-1-residences-taman-daya/hero.jpg",
    location: "Taman Daya",
    price: "RM300k to RM600k",
    distance: "Taman Daya",
    feature: "Completed",
    badges: ["New Launch", "Freehold"],
    
  },
  {
    slug: 'd-secret-garden-2-taman-kempas-indah',
    name: "D Secret Garden 2 Taman Kempas Indah",
    city: 'johor-bahru',
    area: 'taman-kempas-indah',
    status: 'completed',
    tenure: 'freehold',
    image: "/images/properties/d-secret-garden-2-taman-kempas-indah/hero.jpg",
    location: "Taman Kempas Indah",
    price: "RM300K to Rm600K",
    distance: "Taman Kempas Indah",
    feature: "Completed",
    badges: ["New Launch", "Freehold", "Foreigner Eligible"],
    
  },
  {
    slug: 'bee-development-nusajaya',
    name: "Bee Development Nusajaya",
    city: 'johor-bahru',
    area: 'nusajaya',
    status: 'completed',
    tenure: 'freehold',
    image: "/images/properties/bee-development-nusajaya/hero.jpg",
    location: "Iskandar Puteri",
    price: "RM800k to RM2mil",
    distance: "Nusajaya",
    feature: "Completed",
    badges: ["New Launch", "Freehold", "Foreigner Eligible"],
    
  },
  {
    slug: 'fraser-heights-gelang-patah',
    name: "Fraser Heights Gelang Patah",
    city: 'johor-bahru',
    area: 'gelang-patah',
    status: 'completed',
    tenure: 'freehold',
    image: "/images/properties/fraser-heights-gelang-patah/hero.jpg",
    location: "Gelang Patah",
    price: "RM680k to RM780K",
    distance: "Gelang Patah",
    feature: "Completed",
    badges: ["New Launch", "Freehold"],
    
  },
  {
    slug: 'isola-coast-senibong-cove',
    name: "Isola Coast Senibong Cove",
    city: 'johor-bahru',
    area: 'senibong-cove',
    status: 'completed',
    tenure: 'freehold',
    image: "/images/properties/isola-coast-senibong-cove/hero.jpg",
    location: "Senibong Cove",
    price: "RM600K to Rm3mil",
    distance: "Senibong Cove",
    feature: "Completed",
    badges: ["Completed", "Freehold", "Foreigner Eligible"],

  },
  {
    slug: 'sunway-majestic-ara-soho',
    name: "Sunway Majestic Ara SOHO",
    city: 'johor-bahru',
    area: 'jalan-yahya-awal',
    status: 'new-launch',
    tenure: 'freehold',
    image: "/images/properties/sunway-majestic-ara-soho/hero.jpg",
    location: "Jalan Yahya Awal",
    price: "RM350K to RM800K",
    distance: "",
    feature: "Studio / 1 Bedroom / 2 Bedrooms / 3 Bedrooms",
    badges: ["Upcoming", "Freehold", "Foreigner Eligible"],
  },
  {
    slug: 'central-park-country-garden',
    name: "Central Park Country Garden",
    city: 'johor-bahru',
    area: 'taman-damansara-aliff',
    status: 'completed',
    tenure: 'freehold',
    image: "/images/properties/central-park-country-garden/hero.jpg",
    location: "Taman Damansara Aliff",
    price: "RM300k to RM900k",
    distance: "",
    feature: "1+1 Bedroom / 2 Bedrooms / 3 Bedrooms / 4+1 Bedroo",
    badges: ["Completed", "Freehold"],
  },
  {
    slug: 'richmond-mayor-mount-austin',
    name: "Richmond Mayor Mount Austin",
    city: 'johor-bahru',
    area: 'taman-mount-austin',
    status: 'new-launch',
    tenure: 'freehold',
    image: "/images/properties/richmond-mayor-mount-austin/hero.jpg",
    location: "Taman Mount Austin",
    price: "RM580K to RM1.3mil",
    distance: "",
    feature: "Studio / 2 bedrooms / 3 bedrooms",
    badges: ["Upcoming", "Freehold", "Foreigner Eligible"],
  },
  {
    slug: 'eco-tropics',
    name: "Eco Tropics",
    city: 'johor-bahru',
    area: 'pasir-gudang-masai',
    status: 'completed',
    tenure: 'freehold',
    image: "/images/properties/eco-tropics/hero.jpg",
    location: "Pasir Gudang / Masai",
    price: "RM500k to RM700K",
    distance: "",
    feature: "Terrace House",
    badges: ["Completed", "Freehold"],
  },
];

export function getVisibleListings() {
  return propertyListings.filter(p => !p.hidden)
}
export function getListingsByCity(city: string) {
  return getVisibleListings().filter(p => p.city === city)
}
export function getListingBySlug(slug: string) {
  return propertyListings.find(p => p.slug === slug)
}
export function searchListings(query: string) {
  const q = query.toLowerCase()
  return getVisibleListings().filter(p => p.name.toLowerCase().includes(q))
}
export const areas: Record<string, { value: string; label: string }[]> = {
  'johor-bahru': [
    { value: 'bayu-puteri', label: 'Bayu Puteri' },
    { value: 'bukit-chagar', label: 'Bukit Chagar' },
    { value: 'bukit-senyum', label: 'Bukit Senyum' },
    { value: 'country-garden', label: 'Country Garden' },
    { value: 'crest-austin', label: 'Crest Austin' },
    { value: 'danga-bay', label: 'Danga Bay' },
    { value: 'eco-tropics-pasir-gudang', label: 'Eco Tropics Pasir Gudang' },
    { value: 'forest-city', label: 'Forest City' },
    { value: 'forest-city-iskandar-puteri', label: 'Forest City Iskandar Puteri' },
    { value: 'gelang-patah', label: 'Gelang Patah' },
    { value: 'iskandar-puteri', label: 'Iskandar Puteri' },
    { value: 'jalan-yahya-awal', label: 'Jalan Yahya Awal' },
    { value: 'jln-abdul-samad', label: 'Jln Abdul Samad' },
    { value: 'leisure-farm', label: 'Leisure Farm' },
    { value: 'lido-waterfront-boulevard', label: 'Lido Waterfront Boulevard' },
    { value: 'mbw-city', label: 'Mbw City' },
    { value: 'medini-iskandar-puteri', label: 'Medini Iskandar Puteri' },
    { value: 'nusajaya', label: 'Nusajaya' },
    { value: 'pasir-gudang', label: 'Pasir Gudang' },
    { value: 'permas-jaya', label: 'Permas Jaya' },
    { value: 'puteri-harbour', label: 'Puteri Harbour' },
    { value: 'senibong-cove', label: 'Senibong Cove' },
    { value: 'southkey', label: 'Southkey' },
    { value: 'taman-daya', label: 'Taman Daya' },
    { value: 'taman-kempas-indah', label: 'Taman Kempas Indah' },
    { value: 'taman-pelangi', label: 'Taman Pelangi' },
    { value: 'taman-ponderosa', label: 'Taman Ponderosa' },
    { value: 'taman-sentosa', label: 'Taman Sentosa' },
    { value: 'taman-suria', label: 'Taman Suria' },
  ],
  'kuala-lumpur': [
    { value: 'bandar-tasik-selatan', label: 'Bandar Tasik Selatan' },
    { value: 'bangsar', label: 'Bangsar' },
    { value: 'bukit-bintang', label: 'Bukit Bintang' },
    { value: 'bukit-jalil', label: 'Bukit Jalil' },
    { value: 'cheras', label: 'Cheras' },
    { value: 'desa-pandan', label: 'Desa Pandan' },
    { value: 'desa-petaling', label: 'Desa Petaling' },
    { value: 'jalan-klang-lama', label: 'Jalan Klang Lama' },
    { value: 'kepong', label: 'Kepong' },
    { value: 'kl-city-centre', label: 'Kl City Centre' },
    { value: 'mont-kiara', label: 'Mont Kiara' },
    { value: 'segambut', label: 'Segambut' },
    { value: 'sentul', label: 'Sentul' },
    { value: 'seputeh', label: 'Seputeh' },
    { value: 'setapak', label: 'Setapak' },
    { value: 'taman-desa', label: 'Taman Desa' },
  ],
  'penang': [
    { value: 'ayer-itam', label: 'Ayer Itam' },
    { value: 'bagan-dalam', label: 'Bagan Dalam' },
    { value: 'batu-ferringhi', label: 'Batu Ferringhi' },
    { value: 'bayan-lepas', label: 'Bayan Lepas' },
    { value: 'bukit-gambier', label: 'Bukit Gambier' },
    { value: 'gelugor', label: 'Gelugor' },
    { value: 'george-town', label: 'George Town' },
    { value: 'seberang-jaya', label: 'Seberang Jaya' },
    { value: 'tun-abdullah', label: 'Tun Abdullah' },
  ],
}

